/* ============================================================
   data.refs.js — "อ่านเพิ่ม" ท้ายแท็บสุดท้ายของทุกหน้าที่ยังไม่มี
   เดิมลิงก์อ้างอิงกระจายอยู่กลางหน้า (ส่วนใหญ่ในแท็บทฤษฎี) จนหายาก
   ไฟล์นี้เติมบล็อก links ไว้ท้าย eval ให้ที่เดียวกันทุกหน้า
   ต่อท้ายทั้งฝั่งไทยและอังกฤษพร้อมกัน จำนวนบล็อกจึงยังตรงกันเสมอ
   ============================================================ */
(function () {
  var REFS = {
    libft: [
      ["man7 — string(3): ทั้งตระกูล str* และ mem*", "man7 — string(3): the whole str* and mem* family",
       "https://man7.org/linux/man-pages/man3/string.3.html",
       "ค่าคืนและพฤติกรรมขอบของทุกฟังก์ชันที่ต้อง re-implement",
       "Return values and edge behaviour for every function you must re-implement"],
      ["cppreference — Null-terminated byte strings", "cppreference — Null-terminated byte strings",
       "https://en.cppreference.com/w/c/string/byte",
       "เทียบข้อกำหนดตามมาตรฐาน ไม่ใช่แค่พฤติกรรมของ glibc",
       "The standard's requirements, not just what glibc happens to do"],
      ["man7 — memcpy(3) กับข้อห้ามเรื่องพื้นที่ทับกัน", "man7 — memcpy(3) and the overlap prohibition",
       "https://man7.org/linux/man-pages/man3/memcpy.3.html",
       "เหตุผลที่ต้องมี memmove แยกออกมาต่างหาก",
       "Why memmove has to exist as a separate function"],
      ["GNU C Library — Memory Allocation", "GNU C Library — Memory Allocation",
       "https://www.gnu.org/software/libc/manual/html_node/Memory-Allocation.html",
       "malloc/calloc/realloc/free และกฎความเป็นเจ้าของ",
       "malloc/calloc/realloc/free and the ownership rules"],
      ["man7 — malloc(3)", "man7 — malloc(3)",
       "https://man7.org/linux/man-pages/man3/malloc.3.html",
       "calloc ตรวจการล้นของ nmemb * size ให้ ต่างจาก malloc",
       "calloc checks nmemb * size for overflow; malloc does not"]
    ],
    ft_printf: [
      ["man7 — stdarg(3)", "man7 — stdarg(3)",
       "https://man7.org/linux/man-pages/man3/stdarg.3.html",
       "va_start / va_arg / va_end และข้อบังคับว่าต้องมีพารามิเตอร์ที่มีชื่อ",
       "va_start / va_arg / va_end, and why a named parameter is mandatory"],
      ["man7 — printf(3) รูปแบบ conversion ทั้งหมด", "man7 — printf(3), every conversion",
       "https://man7.org/linux/man-pages/man3/printf.3.html",
       "ลำดับ flag, width, precision และความหมายของค่าที่คืน",
       "The order of flags, width and precision, and what the return value means"],
      ["cppreference — Variadic arguments", "cppreference — Variadic arguments",
       "https://en.cppreference.com/w/c/variadic",
       "default argument promotion ที่ทำให้ %c ต้องรับเป็น int",
       "The default argument promotions that force %c to be read as an int"],
      ["GNU C Library — Formatted Output", "GNU C Library — Formatted Output",
       "https://www.gnu.org/software/libc/manual/html_node/Formatted-Output.html",
       "อธิบายแต่ละ conversion พร้อมตัวอย่างที่อ่านง่ายกว่า man",
       "Each conversion explained with examples, more readable than the man page"],
      ["man7 — write(2)", "man7 — write(2)",
       "https://man7.org/linux/man-pages/man2/write.2.html",
       "เขียนได้ไม่ครบก็เป็นไปได้ ค่าคืนจึงต้องเอามานับ",
       "A short write is possible, which is why the return value must be counted"]
    ],
    get_next_line: [
      ["man7 — read(2)", "man7 — read(2)",
       "https://man7.org/linux/man-pages/man2/read.2.html",
       "ค่าคืน 3 แบบ: >0, 0 คือ EOF, <0 คือ error",
       "Three meanings for the return value: >0, 0 for EOF, and negative for an error"],
      ["cppreference — Storage duration และ static", "cppreference — Storage duration and static",
       "https://en.cppreference.com/w/c/language/storage_duration",
       "ทำไมตัวแปร static ถึงอยู่รอดข้ามการเรียกฟังก์ชัน",
       "Why a static variable survives between calls"],
      ["man7 — open(2)", "man7 — open(2)",
       "https://man7.org/linux/man-pages/man2/open.2.html",
       "fd คืออะไร และทำไมเวอร์ชัน bonus ต้องแยก stash ต่อ fd",
       "What a descriptor is, and why the bonus needs one stash per fd"],
      ["GNU C Library — File Descriptors", "GNU C Library — File Descriptors",
       "https://www.gnu.org/software/libc/manual/html_node/Low_002dLevel-I_002fO.html",
       "I/O ระดับล่างเทียบกับ stdio ที่มี buffer ให้เอง",
       "Low-level I/O compared with stdio, which buffers for you"],
      ["Valgrind quick start", "Valgrind quick start",
       "https://valgrind.org/docs/manual/quick-start.html",
       "โปรเจกต์นี้ leak ง่ายที่สุดตอนต่อสตริง — ตรวจทุกครั้ง",
       "This project leaks most easily while joining strings — check every time"]
    ],
    push_swap: [
      ["Wikipedia — Comparison sort และขอบล่าง n log n", "Wikipedia — Comparison sort and the n log n bound",
       "https://en.wikipedia.org/wiki/Comparison_sort",
       "ที่มาของขอบล่างเชิงทฤษฎีที่ใช้อธิบายจำนวน operation",
       "Where the theoretical lower bound on your operation count comes from"],
      ["Big-O cheat sheet", "Big-O cheat sheet",
       "https://www.bigocheatsheet.com/",
       "เทียบความซับซ้อนของอัลกอริทึมเรียงลำดับแบบเห็นภาพ",
       "A visual comparison of sorting complexities"],
      ["Wikipedia — Insertion sort", "Wikipedia — Insertion sort",
       "https://en.wikipedia.org/wiki/Insertion_sort",
       "แกนของ Turkish sort คือการแทรกกลับเข้าที่ที่ถูก",
       "The core of the Turkish sort is inserting each value back in the right place"],
      ["man7 — write(2)", "man7 — write(2)",
       "https://man7.org/linux/man-pages/man2/write.2.html",
       "ฟังก์ชันเดียวที่ใช้พิมพ์ op ได้ตามรายการที่อนุญาต",
       "The only function the allowed list gives you for printing operations"],
      ["Valgrind quick start", "Valgrind quick start",
       "https://valgrind.org/docs/manual/quick-start.html",
       "ทุก error path ต้อง free stack ทั้งสองก้อนก่อน exit",
       "Every error path must free both stacks before exiting"]
    ],
    pipex: [
      ["man7 — pipe(2)", "man7 — pipe(2)",
       "https://man7.org/linux/man-pages/man2/pipe.2.html",
       "pfd[0] อ่าน pfd[1] เขียน และเรื่อง reference count ของปลายท่อ",
       "pfd[0] reads, pfd[1] writes, and how the ends are reference counted"],
      ["man7 — dup2(2)", "man7 — dup2(2)",
       "https://man7.org/linux/man-pages/man2/dup2.2.html",
       "เปลี่ยน stdin/stdout ของลูกโดยไม่แตะโค้ดของคำสั่งที่รัน",
       "Redirect a child's stdin/stdout without touching the command's own code"],
      ["man7 — execve(2)", "man7 — execve(2)",
       "https://man7.org/linux/man-pages/man2/execve.2.html",
       "แทนที่ image ของโปรเซส — คืนค่ามาเมื่อไหร่แปลว่าล้มเหลว",
       "Replaces the process image; if it returns at all, it failed"],
      ["man7 — fork(2)", "man7 — fork(2)",
       "https://man7.org/linux/man-pages/man2/fork.2.html",
       "ลูกได้สำเนาของตาราง fd ไปด้วย จึงต้องปิดให้ครบทั้งสองฝั่ง",
       "The child inherits a copy of the descriptor table, so both sides must close"],
      ["man7 — waitpid(2)", "man7 — waitpid(2)",
       "https://man7.org/linux/man-pages/man2/wait.2.html",
       "เก็บสถานะออกของลูก และที่มาของ exit code ที่ต้องคืน",
       "Reap the children and derive the exit code you must return"]
    ],
    so_long: [
      ["MiniLibX — เอกสารของ 42", "MiniLibX — the 42 documentation",
       "https://harm-smits.github.io/42docs/libs/minilibx",
       "window, image, hook และ event loop อธิบายครบในที่เดียว",
       "Windows, images, hooks and the event loop, all in one place"],
      ["Wikipedia — Flood fill", "Wikipedia — Flood fill",
       "https://en.wikipedia.org/wiki/Flood_fill",
       "อัลกอริทึมที่ใช้ตรวจว่าเดินถึงของสะสมและทางออกครบไหม",
       "The algorithm behind checking that every collectible and the exit are reachable"],
      ["Wikipedia — Depth-first search", "Wikipedia — Depth-first search",
       "https://en.wikipedia.org/wiki/Depth-first_search",
       "รูปแบบ recursive ที่ flood fill ใช้ พร้อมความลึกที่ต้องระวัง",
       "The recursive shape flood fill uses, and the stack depth to watch"],
      ["Wikipedia — Breadth-first search", "Wikipedia — Breadth-first search",
       "https://en.wikipedia.org/wiki/Breadth-first_search",
       "ทางเลือกที่ไม่ระเบิด stack เมื่อแผนที่ใหญ่มาก",
       "The alternative that will not blow the stack on a very large map"],
      ["XPM file format", "XPM file format",
       "https://en.wikipedia.org/wiki/X_PixMap",
       "รูปแบบภาพเดียวที่ MiniLibX โหลดได้",
       "The only image format MiniLibX can load"]
    ],
    fractol: [
      ["Wikipedia — Mandelbrot set", "Wikipedia — Mandelbrot set",
       "https://en.wikipedia.org/wiki/Mandelbrot_set",
       "นิยาม, ทฤษฎีบทรัศมีหนี และที่มาของเงื่อนไข |z| > 2",
       "The definition, the escape radius theorem, and where |z| > 2 comes from"],
      ["Wikipedia — Julia set", "Wikipedia — Julia set",
       "https://en.wikipedia.org/wiki/Julia_set",
       "ความสัมพันธ์ระหว่าง c ที่คงที่กับรูปร่างที่ได้",
       "How a fixed c relates to the shape you get"],
      ["Plotting algorithms for the Mandelbrot set", "Plotting algorithms for the Mandelbrot set",
       "https://en.wikipedia.org/wiki/Plotting_algorithms_for_the_Mandelbrot_set",
       "escape time, smooth coloring และการไล่สีที่ไม่เป็นแถบ",
       "Escape time, smooth colouring, and how to avoid banding"],
      ["Wikipedia — IEEE 754", "Wikipedia — IEEE 754",
       "https://en.wikipedia.org/wiki/IEEE_754",
       "ทำไมซูมลึกมากแล้วภาพเริ่มเป็นบล็อก",
       "Why the image turns blocky once you zoom deeply enough"],
      ["MiniLibX — เอกสารของ 42", "MiniLibX — the 42 documentation",
       "https://harm-smits.github.io/42docs/libs/minilibx",
       "การเขียนลง buffer ของ image ตรง ๆ แทนการเรียกทีละ pixel",
       "Writing into the image buffer directly instead of calling per pixel"]
    ],
    minitalk: [
      ["man7 — signal(7): ภาพรวมของสัญญาณทั้งระบบ", "man7 — signal(7): the whole picture",
       "https://man7.org/linux/man-pages/man7/signal.7.html",
       "สัญญาณไม่เข้าคิว ส่งรัวแล้วหายได้ ซึ่งเป็นหัวใจของโจทย์",
       "Signals do not queue, so a burst can be lost — the heart of this project"],
      ["man7 — sigaction(2)", "man7 — sigaction(2)",
       "https://man7.org/linux/man-pages/man2/sigaction.2.html",
       "ทำไมถึงควรใช้แทน signal() และ SA_SIGINFO ให้อะไรเพิ่ม",
       "Why it is preferred over signal(), and what SA_SIGINFO adds"],
      ["man7 — signal-safety(7)", "man7 — signal-safety(7)",
       "https://man7.org/linux/man-pages/man7/signal-safety.7.html",
       "รายชื่อฟังก์ชันที่เรียกใน handler ได้จริง — printf ไม่อยู่ในนั้น",
       "The list of functions a handler may call — printf is not among them"],
      ["man7 — kill(2)", "man7 — kill(2)",
       "https://man7.org/linux/man-pages/man2/kill.2.html",
       "ส่งสัญญาณไปหา pid และ error ที่ต้องตรวจ",
       "Sending a signal to a pid, and the errors to check"],
      ["man7 — pause(2)", "man7 — pause(2)",
       "https://man7.org/linux/man-pages/man2/pause.2.html",
       "รอสัญญาณโดยไม่เผา CPU ต่างจาก while ว่าง ๆ",
       "Waiting for a signal without burning CPU, unlike an empty loop"]
    ],
    fdf: [
      ["Wikipedia — Isometric projection", "Wikipedia — Isometric projection",
       "https://en.wikipedia.org/wiki/Isometric_projection",
       "ที่มาของมุม 30° และสูตรที่ใช้แปลงพิกัด",
       "Where the 30 degrees comes from, and the formula behind the transform"],
      ["Wikipedia — Bresenham's line algorithm", "Wikipedia — Bresenham's line algorithm",
       "https://en.wikipedia.org/wiki/Bresenham%27s_line_algorithm",
       "ลากเส้นด้วยจำนวนเต็มล้วน ไม่ต้องใช้ทศนิยม",
       "Drawing a line with integers only, no floating point needed"],
      ["Wikipedia — Rotation matrix", "Wikipedia — Rotation matrix",
       "https://en.wikipedia.org/wiki/Rotation_matrix",
       "การหมุนรอบแกน x, y, z สำหรับ bonus",
       "Rotation about the x, y and z axes for the bonus"],
      ["Wikipedia — Linear interpolation", "Wikipedia — Linear interpolation",
       "https://en.wikipedia.org/wiki/Linear_interpolation",
       "ไล่สีระหว่างปลายสองด้านของเส้น",
       "Blending colour between the two ends of a line"],
      ["MiniLibX — เอกสารของ 42", "MiniLibX — the 42 documentation",
       "https://harm-smits.github.io/42docs/libs/minilibx",
       "hook ของคีย์บอร์ดและการปิดหน้าต่างให้สะอาด",
       "Keyboard hooks and closing the window cleanly"]
    ],
    philosophers: [
      ["Wikipedia — Dining philosophers problem", "Wikipedia — Dining philosophers problem",
       "https://en.wikipedia.org/wiki/Dining_philosophers_problem",
       "ตัวโจทย์ดั้งเดิมและวิธีแก้ที่รู้จักกันดี",
       "The original problem and its well-known solutions"],
      ["Wikipedia — Deadlock และเงื่อนไข Coffman", "Wikipedia — Deadlock and the Coffman conditions",
       "https://en.wikipedia.org/wiki/Deadlock",
       "4 เงื่อนไขที่ต้องเกิดพร้อมกัน — ตัดข้อใดข้อหนึ่งก็พอ",
       "The four conditions that must hold at once — breaking any one is enough"],
      ["man7 — pthread_mutex_lock(3)", "man7 — pthread_mutex_lock(3)",
       "https://man7.org/linux/man-pages/man3/pthread_mutex_lock.3p.html",
       "พฤติกรรมตอนล็อกซ้ำและชนิดของ mutex",
       "What happens on a re-lock, and the mutex types"],
      ["man7 — pthread_create(3)", "man7 — pthread_create(3)",
       "https://man7.org/linux/man-pages/man3/pthread_create.3.html",
       "การส่งอาร์กิวเมนต์เข้า thread และการ join กลับ",
       "Passing an argument into a thread and joining it back"],
      ["man7 — gettimeofday(2)", "man7 — gettimeofday(2)",
       "https://man7.org/linux/man-pages/man2/gettimeofday.2.html",
       "จับเวลาเป็นมิลลิวินาทีสำหรับตรวจการอดตาย",
       "Millisecond timing for the starvation check"]
    ],
    minishell: [
      ["Bash Reference Manual", "Bash Reference Manual",
       "https://www.gnu.org/software/bash/manual/bash.html",
       "พฤติกรรมอ้างอิงเวลาไม่แน่ใจว่า shell จริงทำอะไร",
       "The reference behaviour whenever you are unsure what a real shell does"],
      ["POSIX Shell Command Language", "POSIX Shell Command Language",
       "https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html",
       "ไวยากรณ์ที่เป็นทางการ: token, quoting, redirection",
       "The formal grammar: tokens, quoting, redirection"],
      ["GNU Readline library", "GNU Readline library",
       "https://tiswww.case.edu/php/chet/readline/rltop.html",
       "readline, add_history และเรื่อง memory ที่ต้องจัดการเอง",
       "readline, add_history, and the memory you are responsible for"],
      ["man7 — execve(2)", "man7 — execve(2)",
       "https://man7.org/linux/man-pages/man2/execve.2.html",
       "การค้น PATH และ envp ที่ต้องประกอบเอง",
       "PATH resolution and the envp you must assemble yourself"],
      ["man7 — signal(7)", "man7 — signal(7)",
       "https://man7.org/linux/man-pages/man7/signal.7.html",
       "Ctrl-C ระหว่างรอ readline กับระหว่างรันคำสั่งต่างกัน",
       "Ctrl-C behaves differently while waiting in readline and while a command runs"]
    ],
    minirt: [
      ["Scratchapixel — Ray-sphere intersection", "Scratchapixel — Ray-sphere intersection",
       "https://www.scratchapixel.com/lessons/3d-basic-rendering/minimal-ray-tracer-rendering-simple-shapes/ray-sphere-intersection.html",
       "ที่มาของสมการกำลังสองและการเลือกรากที่ถูก",
       "Where the quadratic comes from and which root to take"],
      ["Wikipedia — Ray tracing (graphics)", "Wikipedia — Ray tracing (graphics)",
       "https://en.wikipedia.org/wiki/Ray_tracing_(graphics)",
       "ภาพรวมว่าทำไมยิง ray จากกล้องไม่ใช่จากไฟ",
       "The overview of why rays start at the camera rather than the light"],
      ["Wikipedia — Phong reflection model", "Wikipedia — Phong reflection model",
       "https://en.wikipedia.org/wiki/Phong_reflection_model",
       "ambient + diffuse + specular และความหมายของแต่ละพจน์",
       "Ambient plus diffuse plus specular, and what each term means"],
      ["Wikipedia — Shadow acne และ shadow bias", "Wikipedia — Shadow acne and bias",
       "https://en.wikipedia.org/wiki/Shadow_mapping",
       "ทำไมต้องขยับจุดเริ่มของ shadow ray ออกตาม normal",
       "Why the shadow ray's origin must be offset along the normal"],
      ["MiniLibX — เอกสารของ 42", "MiniLibX — the 42 documentation",
       "https://harm-smits.github.io/42docs/libs/minilibx",
       "เขียนลง buffer ของ image แล้วค่อยส่งเข้าหน้าต่างครั้งเดียว",
       "Write into the image buffer, then push it to the window once"]
    ],
    cub3d: [
      ["Lode's Computer Graphics Tutorial — Raycasting", "Lode's Computer Graphics Tutorial — Raycasting",
       "https://lodev.org/cgtutor/raycasting.html",
       "ต้นฉบับของอัลกอริทึม DDA และการแก้ fisheye ที่โปรเจกต์นี้อิง",
       "The original DDA walk and fisheye correction this project is based on"],
      ["Lode's tutorial — Textured raycaster", "Lode's tutorial — Textured raycaster",
       "https://lodev.org/cgtutor/raycasting2.html",
       "การเลือกคอลัมน์ texture จาก wallX และการพลิกด้าน",
       "Choosing the texture column from wallX, and mirroring per side"],
      ["Wikipedia — Ray casting", "Wikipedia — Ray casting",
       "https://en.wikipedia.org/wiki/Ray_casting",
       "ความต่างระหว่าง ray casting กับ ray tracing เต็มรูปแบบ",
       "How ray casting differs from full ray tracing"],
      ["Wikipedia — Digital differential analyzer", "Wikipedia — Digital differential analyzer",
       "https://en.wikipedia.org/wiki/Digital_differential_analyzer_(graphics_algorithm)",
       "การเดินทีละช่องตารางโดยไม่พลาดผนัง",
       "Stepping cell by cell without ever missing a wall"],
      ["MiniLibX — เอกสารของ 42", "MiniLibX — the 42 documentation",
       "https://harm-smits.github.io/42docs/libs/minilibx",
       "loop hook, key hook และการปิดหน้าต่างโดยไม่ leak",
       "The loop hook, key hooks, and closing the window without leaking"]
    ],
    cpp_module_00: [
      ["cppreference — Classes", "cppreference — Classes",
       "https://en.cppreference.com/w/cpp/language/classes",
       "โครงของคลาส สมาชิก และระดับการเข้าถึง",
       "Class structure, members and access levels"],
      ["isocpp — C++ FAQ", "isocpp — C++ FAQ",
       "https://isocpp.org/faq",
       "คำถามพื้นฐานที่ผู้ตรวจชอบถาม ตอบโดยคนออกแบบภาษา",
       "The basic questions evaluators ask, answered by the language's designers"],
      ["cppreference — static members", "cppreference — static members",
       "https://en.cppreference.com/w/cpp/language/static",
       "สมาชิกที่เป็นของคลาส ไม่ใช่ของอ็อบเจกต์ และการนิยามนอกคลาส",
       "Members that belong to the class rather than an object, and defining them out of line"],
      ["cppreference — std::string", "cppreference — std::string",
       "https://en.cppreference.com/w/cpp/string/basic_string",
       "แทนที่ char * ทั้งหมดในสาย C++ ของ 42",
       "It replaces every char * across the 42 C++ modules"],
      ["cppreference — Input/output manipulators", "cppreference — Input/output manipulators",
       "https://en.cppreference.com/w/cpp/io/manip",
       "setw, setfill และการจัดคอลัมน์ของ phonebook",
       "setw, setfill, and lining up the phonebook's columns"]
    ],
    cpp_module_01: [
      ["cppreference — new expression", "cppreference — new expression",
       "https://en.cppreference.com/w/cpp/language/new",
       "stack เทียบ heap และคู่ของ new/delete ที่ห้ามสลับ",
       "Stack versus heap, and the new/delete pairing you must not cross"],
      ["cppreference — References", "cppreference — References",
       "https://en.cppreference.com/w/cpp/language/reference",
       "ผูกครั้งเดียว เป็น NULL ไม่ได้ และต่างจาก pointer ยังไง",
       "Bound once, never null, and how that differs from a pointer"],
      ["isocpp FAQ — References", "isocpp FAQ — References",
       "https://isocpp.org/wiki/faq/references",
       "คำตอบว่าเมื่อไหร่ควรใช้ reference เมื่อไหร่ควรใช้ pointer",
       "When to choose a reference and when to choose a pointer"],
      ["cppreference — Pointers to members", "cppreference — Pointers to members",
       "https://en.cppreference.com/w/cpp/language/pointer",
       "ไวยากรณ์ .* และ ->* ที่ใช้ทำตาราง method ใน Harl",
       "The .* and ->* syntax behind Harl's method table"],
      ["cppreference — std::ifstream / std::ofstream", "cppreference — std::ifstream / std::ofstream",
       "https://en.cppreference.com/w/cpp/io/basic_fstream",
       "stream เป็น RAII แต่ยังต้องเช็ค is_open() เสมอ",
       "Streams are RAII, but is_open() still has to be checked"]
    ],
    cpp_module_02: [
      ["cppreference — Operator overloading", "cppreference — Operator overloading",
       "https://en.cppreference.com/w/cpp/language/operators",
       "ตัวไหนต้องเป็น method ตัวไหนต้องเป็นฟังก์ชันอิสระ",
       "Which operators must be members and which must be free functions"],
      ["isocpp FAQ — Operator overloading", "isocpp FAQ — Operator overloading",
       "https://isocpp.org/wiki/faq/operator-overloading",
       "กติกาที่ทำให้ operator ที่เขียนเองไม่สร้างความประหลาดใจ",
       "The rules that keep a custom operator from surprising its user"],
      ["cppreference — Rule of three", "cppreference — Rule of three",
       "https://en.cppreference.com/w/cpp/language/rule_of_three",
       "ที่มาของ Orthodox Canonical Form ที่ 42 บังคับ",
       "The origin of the Orthodox Canonical Form that 42 mandates"],
      ["Wikipedia — Fixed-point arithmetic", "Wikipedia — Fixed-point arithmetic",
       "https://en.wikipedia.org/wiki/Fixed-point_arithmetic",
       "การเก็บเศษด้วยจำนวนเต็มและการปรับสเกลตอนคูณหาร",
       "Storing a fraction in an integer, and rescaling on multiply and divide"],
      ["Wikipedia — Cross product", "Wikipedia — Cross product",
       "https://en.wikipedia.org/wiki/Cross_product",
       "เครื่องหมายของ cross product ที่ใช้ตัดสินว่าจุดอยู่ในสามเหลี่ยม",
       "The sign of the cross product that decides whether a point is inside a triangle"]
    ],
    cpp_module_03: [
      ["cppreference — Derived classes", "cppreference — Derived classes",
       "https://en.cppreference.com/w/cpp/language/derived_class",
       "การสืบทอด ระดับการเข้าถึง และ virtual inheritance",
       "Inheritance, access levels, and virtual inheritance"],
      ["isocpp FAQ — Inheritance basics", "isocpp FAQ — Inheritance basics",
       "https://isocpp.org/wiki/faq/basics-of-inheritance",
       "อะไรถูกสืบทอดบ้าง และอะไรไม่ถูกสืบทอด",
       "What is inherited and what is not"],
      ["Wikipedia — Multiple inheritance และ diamond problem", "Wikipedia — Multiple inheritance and the diamond problem",
       "https://en.wikipedia.org/wiki/Multiple_inheritance",
       "ที่มาของปัญหาที่ DiamondTrap เจอโดยตรง",
       "The exact problem DiamondTrap runs into"],
      ["cppreference — Constructors and member initializer lists", "cppreference — Constructors and member initializer lists",
       "https://en.cppreference.com/w/cpp/language/constructor",
       "ทำไมต้องเรียก constructor ของแม่ใน initializer list",
       "Why the base constructor belongs in the initializer list"],
      ["cppreference — Integer conversions", "cppreference — Integer conversions",
       "https://en.cppreference.com/w/c/language/conversion",
       "unsigned วนกลับเมื่อลบเกินศูนย์ ซึ่งเป็นกับดักของโจทย์",
       "Unsigned wrap-around below zero, the trap this module plants"]
    ],
    cpp_module_04: [
      ["cppreference — virtual function specifier", "cppreference — virtual function specifier",
       "https://en.cppreference.com/w/cpp/language/virtual",
       "dynamic dispatch และเหตุผลที่ base ต้องมี virtual destructor",
       "Dynamic dispatch, and why a base class needs a virtual destructor"],
      ["isocpp FAQ — Virtual functions", "isocpp FAQ — Virtual functions",
       "https://isocpp.org/wiki/faq/virtual-functions",
       "คำอธิบายว่า vtable ทำงานยังไงในทางปฏิบัติ",
       "How a vtable actually works in practice"],
      ["cppreference — Abstract class", "cppreference — Abstract class",
       "https://en.cppreference.com/w/cpp/language/abstract_class",
       "pure virtual และคลาสที่สร้างอินสแตนซ์ไม่ได้",
       "Pure virtuals, and classes that cannot be instantiated"],
      ["cppreference — Copy constructors", "cppreference — Copy constructors",
       "https://en.cppreference.com/w/cpp/language/copy_constructor",
       "shallow กับ deep copy และเหตุผลที่ Brain ต้องคัดลอกลึก",
       "Shallow versus deep copy, and why Brain must be copied deeply"],
      ["Wikipedia — Object slicing", "Wikipedia — Object slicing",
       "https://en.wikipedia.org/wiki/Object_slicing",
       "สาเหตุที่ต้องเก็บเป็น pointer หรือ reference ไม่ใช่ค่าตรง ๆ",
       "Why polymorphic objects are held by pointer or reference, never by value"]
    ],
    cpp_module_05: [
      ["cppreference — Exceptions", "cppreference — Exceptions",
       "https://en.cppreference.com/w/cpp/language/exceptions",
       "throw, try, catch และการคลาย stack",
       "throw, try, catch, and stack unwinding"],
      ["cppreference — std::exception", "cppreference — std::exception",
       "https://en.cppreference.com/w/cpp/error/exception",
       "ลำดับชั้นของ exception มาตรฐานและ what()",
       "The standard exception hierarchy and what()"],
      ["isocpp FAQ — Exceptions and error handling", "isocpp FAQ — Exceptions and error handling",
       "https://isocpp.org/wiki/faq/exceptions",
       "เมื่อไหร่ควรโยน และทำไมต้อง catch ด้วย reference",
       "When to throw, and why you catch by reference"],
      ["Wikipedia — Template method pattern", "Wikipedia — Template method pattern",
       "https://en.wikipedia.org/wiki/Template_method_pattern",
       "รูปแบบที่ execute() ของ AForm ใช้ตรง ๆ",
       "The pattern AForm's execute() implements directly"],
      ["cppreference — const member functions", "cppreference — const member functions",
       "https://en.cppreference.com/w/cpp/language/member_functions",
       "สมาชิกที่เป็น const กับผลกระทบต่อ operator= ",
       "const members, and what they do to operator="]
    ],
    cpp_module_06: [
      ["cppreference — static_cast", "cppreference — static_cast",
       "https://en.cppreference.com/w/cpp/language/static_cast",
       "แปลงระหว่างชนิดที่เกี่ยวข้องกัน ตรวจได้ตอนคอมไพล์",
       "Converting between related types, checked at compile time"],
      ["cppreference — dynamic_cast", "cppreference — dynamic_cast",
       "https://en.cppreference.com/w/cpp/language/dynamic_cast",
       "รุ่น pointer คืน NULL ส่วนรุ่น reference โยน bad_cast",
       "The pointer form returns null; the reference form throws bad_cast"],
      ["cppreference — reinterpret_cast", "cppreference — reinterpret_cast",
       "https://en.cppreference.com/w/cpp/language/reinterpret_cast",
       "ตีความบิตชุดเดิมใหม่ ใช้กับ serialize/deserialize",
       "Reinterpreting the same bits, as serialize/deserialize do"],
      ["cppreference — const_cast", "cppreference — const_cast",
       "https://en.cppreference.com/w/cpp/language/const_cast",
       "ตัวที่สี่ที่ผู้ตรวจมักถามให้ครบชุด",
       "The fourth cast, which evaluators ask about to complete the set"],
      ["cppreference — std::uintptr_t", "cppreference — std::uintptr_t",
       "https://en.cppreference.com/w/cpp/types/integer",
       "ชนิดเดียวที่รับประกันว่าเก็บ pointer ได้ครบ",
       "The only type guaranteed to hold a pointer"]
    ],
    cpp_module_07: [
      ["cppreference — Templates", "cppreference — Templates",
       "https://en.cppreference.com/w/cpp/language/templates",
       "instantiation และเหตุผลที่ template ต้องอยู่ใน header",
       "Instantiation, and why templates live in headers"],
      ["isocpp FAQ — Templates", "isocpp FAQ — Templates",
       "https://isocpp.org/wiki/faq/templates",
       "คำถามคลาสสิกรวมทั้ง undefined reference ตอน link",
       "The classic questions, including the link-time undefined reference"],
      ["cppreference — Template argument deduction", "cppreference — Template argument deduction",
       "https://en.cppreference.com/w/cpp/language/template_argument_deduction",
       "ทำไม iter() ถึงไม่ต้องระบุชนิดตอนเรียก",
       "Why iter() needs no explicit type at the call site"],
      ["cppreference — operator[]", "cppreference — operator[]",
       "https://en.cppreference.com/w/cpp/language/operators",
       "ทำไมต้องมีทั้งเวอร์ชัน const และไม่ const",
       "Why both a const and a non-const version are needed"],
      ["cppreference — Rule of three", "cppreference — Rule of three",
       "https://en.cppreference.com/w/cpp/language/rule_of_three",
       "Array<T> ถือหน่วยความจำ จึงต้องครบทั้งสามอย่าง",
       "Array<T> owns memory, so all three are mandatory"]
    ],
    cpp_module_08: [
      ["cppreference — Containers library", "cppreference — Containers library",
       "https://en.cppreference.com/w/cpp/container",
       "ความซับซ้อนและข้อแลกเปลี่ยนของแต่ละ container",
       "The complexity and trade-offs of each container"],
      ["cppreference — Iterator library", "cppreference — Iterator library",
       "https://en.cppreference.com/w/cpp/iterator",
       "ประเภทของ iterator และช่วงแบบ [begin, end)",
       "Iterator categories and the half-open [begin, end) range"],
      ["cppreference — Algorithms library", "cppreference — Algorithms library",
       "https://en.cppreference.com/w/cpp/algorithm",
       "find, sort, min_element และเพื่อนที่ใช้ใน Span",
       "find, sort, min_element and the rest that Span uses"],
      ["cppreference — std::stack", "cppreference — std::stack",
       "https://en.cppreference.com/w/cpp/container/stack",
       "container adaptor และ member c ที่เป็น protected",
       "The container adaptor, and its protected member c"],
      ["cppreference — Dependent names และ typename", "cppreference — Dependent names and typename",
       "https://en.cppreference.com/w/cpp/language/dependent_name",
       "เหตุผลที่ต้องเขียน typename T::iterator",
       "Why you must write typename T::iterator"]
    ],
    cpp_module_09: [
      ["cppreference — std::map", "cppreference — std::map",
       "https://en.cppreference.com/w/cpp/container/map",
       "เรียงตาม key เอง และ lower_bound ที่ใช้หาวันที่ก่อนหน้า",
       "Sorted by key, with the lower_bound used to find the earlier date"],
      ["cppreference — std::stack", "cppreference — std::stack",
       "https://en.cppreference.com/w/cpp/container/stack",
       "โครงสร้างที่เข้ากับ RPN พอดี",
       "The structure RPN maps onto exactly"],
      ["Wikipedia — Reverse Polish notation", "Wikipedia — Reverse Polish notation",
       "https://en.wikipedia.org/wiki/Reverse_Polish_notation",
       "ทำไมถึงไม่ต้องมีวงเล็บและลำดับความสำคัญ",
       "Why it needs neither parentheses nor precedence"],
      ["Wikipedia — Merge-insertion sort (Ford-Johnson)", "Wikipedia — Merge-insertion sort (Ford-Johnson)",
       "https://en.wikipedia.org/wiki/Merge-insertion_sort",
       "ลำดับ Jacobsthal และที่มาของจำนวนการเปรียบเทียบที่ต่ำ",
       "The Jacobsthal sequence and where the low comparison count comes from"],
      ["cppreference — std::vector เทียบ std::deque", "cppreference — std::vector versus std::deque",
       "https://en.cppreference.com/w/cpp/container/deque",
       "เหตุผลที่เวลาของสอง container ออกมาไม่เท่ากัน",
       "Why the two containers time differently"]
    ]
  };

  var HEAD = { th: "อ่านเพิ่ม", en: "Further reading" };
  window.TEACHING_DATA.forEach(function (p) {
    var r = REFS[p.id];
    if (!r || !p.sections.eval) return;
    p.sections.eval.push({ h: HEAD });
    p.sections.eval.push({ links: r.map(function (x) {
      return { label: x[0], url: x[2], note: x[3] };
    }) });
    var en = window.TEACHING_EN[p.id];
    if (en && en.eval) {
      en.eval.push({ h: HEAD });
      en.eval.push({ links: r.map(function (x) {
        return { label: x[1], url: x[2], note: x[4] };
      }) });
    }
  });
})();
