/* ============================================================
   data.flows.js — flow visualizer สำหรับหน้าที่ยังไม่มีของตัวเอง
   (miniRT, cub3D, Fine-tuning, Output Control)
   โครงเดียวกับ FLOWS ใน app.js: { input, steps:[{fn,file,depth,note,data,vars}] }
   ============================================================ */
window.EXTRA_FLOWS = window.EXTRA_FLOWS || {};

window.EXTRA_FLOWS.minirt = {
  input: "./miniRT scenes/sphere.rt",
  steps: [
    { fn: "main()", file: "main.c", depth: 0,
      note: { th: "ตรวจ argc, นามสกุลต้องเป็น `.rt`, แล้วส่งต่อให้ parser — ทุก error path ต้องพิมพ์ขึ้นต้นด้วย `Error` แล้ว free ให้ครบก่อน exit",
              en: "Check argc, require a `.rt` extension, then hand over to the parser — every error path prints a line starting with `Error` and frees everything before exiting." },
      data: "argv[1] = \"scenes/sphere.rt\"",
      vars: [ { n: "t_scene scene", d: { th: "struct ตัวเดียววิ่งทั้งโปรแกรม", en: "one struct travels through the whole program" }, w: true } ] },
    { fn: "parse_scene()", file: "parse.c", depth: 1,
      note: { th: "อ่านทีละบรรทัดด้วย get_next_line แล้วแยกตาม identifier: `A` ambient, `C` camera, `L` light, `sp`/`pl`/`cy` วัตถุ — **A, C, L มีได้อย่างละหนึ่งเท่านั้น**",
              en: "Read line by line with get_next_line and dispatch on the identifier: `A` ambient, `C` camera, `L` light, `sp`/`pl`/`cy` objects — **A, C and L may appear only once each.**" },
      data: "A 0.2 255,255,255\nC -50,0,20 0,0,1 70\nsp 0,0,20 20 255,0,0",
      vars: [ { n: "scene.objs", d: { th: "linked list ของวัตถุทุกชิ้น", en: "a linked list of every object" }, w: true } ] },
    { fn: "setup_camera()", file: "camera.c", depth: 1,
      note: { th: "สร้าง basis จาก forward + world-up ด้วย cross product **ระวังเคส forward ขนานกับ up** (กล้องมองตรงลงพื้น) ต้องเปลี่ยน up สำรอง ไม่งั้น cross ได้เวกเตอร์ศูนย์แล้วภาพดำ",
              en: "Build the basis from forward and world-up with cross products, **guarding the case where forward is parallel to up** (a camera looking straight down) — otherwise the cross product is a zero vector and the image goes black." },
      data: "fov 70° -> scale = tan(35° * π/180)   aspect = W/H",
      vars: [ { n: "right, up, fwd", d: { th: "แกนสามแกนของกล้อง ต้อง normalize ทุกตัว", en: "the camera's three axes, each normalised" }, w: true } ] },
    { fn: "render() — ต่อ 1 pixel", file: "render.c", depth: 1,
      note: { th: "**1 ray ต่อ 1 pixel** (ต่างจาก cub3D ที่ยิงต่อคอลัมน์) แปลงพิกัด pixel เป็นช่วง [-1,1] แล้วสร้างทิศ ray จาก basis ของกล้อง",
              en: "**One ray per pixel** — unlike cub3D, which casts one per column. Map the pixel to [-1,1] and build the ray direction from the camera basis." },
      data: "x=640 y=360  ->  ndc = (0.0, 0.0)  ->  dir = fwd",
      vars: [ { n: "ray", v: "{orig, dir}", d: { th: "dir ต้อง normalize ไม่งั้นระยะ t เพี้ยน", en: "dir must be normalised or every distance t is wrong" }, w: true } ] },
    { fn: "hit_sphere()", file: "inter_sphere.c", depth: 2,
      note: { th: "แทน ray ลงสมการทรงกลมได้สมการกำลังสอง `at² + bt + c = 0` แล้วเลือกรากที่ **น้อยที่สุดที่ยังเป็นบวก** — รากลบคือของที่อยู่ข้างหลังกล้อง",
              en: "Substituting the ray into the sphere equation gives `at² + bt + c = 0`; take the **smallest positive root** — a negative root is behind the camera." },
      data: "disc = b² - 4ac = 1284 > 0  ->  t = 30.2",
      vars: [ { n: "t", v: "30.2", d: { th: "ระยะถึงจุดชนที่ใกล้ที่สุด", en: "distance to the nearest hit" }, w: true } ] },
    { fn: "closest_hit()", file: "render.c", depth: 2,
      note: { th: "ไล่ทุกวัตถุแล้วเก็บ `t` ที่น้อยที่สุด พร้อม normal ที่จุดนั้น — ไม่มีตัวไหนชนเลยก็คืนสีพื้นหลัง",
              en: "Walk every object keeping the smallest `t` together with the normal at that point; if nothing is hit, return the background colour." },
      data: "hit: sphere#1  t=30.2  point=(0,0,20)  normal=(0,0,-1)",
      vars: [ { n: "rec", v: "{t, p, n, color}", d: { th: "ข้อมูลจุดชนที่ส่งต่อให้ shading", en: "the hit record handed to shading" }, w: true } ] },
    { fn: "shade()", file: "light.c", depth: 2,
      note: { th: "ambient + diffuse ตามกฎ Lambert `max(0, dot(n, l))` แล้วยิง shadow ray ไปหาไฟ — ต้อง **ขยับจุดเริ่มออกตาม normal นิดหนึ่ง (epsilon)** ไม่งั้นเกิด shadow acne",
              en: "Ambient plus Lambert diffuse `max(0, dot(n, l))`, then a shadow ray toward the light — **offset its origin along the normal by an epsilon** or you get shadow acne." },
      data: "diffuse = max(0, dot(n,l)) = 0.83   shadow ray: ไม่โดนบัง",
      vars: [ { n: "color", v: "(212, 0, 0)", d: { th: "clamp 0-255 ก่อนแพ็กเป็น int", en: "clamped to 0-255 before packing to an int" }, w: true } ] },
    { fn: "my_mlx_pixel_put()", file: "render.c", depth: 2,
      note: { th: "เขียนลง buffer ของ image เอง (`addr + y*line_len + x*(bpp/8)`) แล้วค่อย `mlx_put_image_to_window` ครั้งเดียวตอนจบ — เรียกทีละ pixel จะช้ามาก",
              en: "Write into the image buffer directly (`addr + y*line_len + x*(bpp/8)`) and call `mlx_put_image_to_window` once at the end — per-pixel calls are painfully slow." },
      data: "วนครบ 1280×720 = 921,600 ray",
      vars: [ { n: "img.addr", d: { th: "buffer เดียว ส่งเข้าหน้าต่างครั้งเดียว", en: "one buffer, pushed to the window once" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cub3d = {
  input: "./cub3D maps/simple.cub   (ผู้เล่นกดปุ่มเดินหน้า)",
  steps: [
    { fn: "parse_cub()", file: "parse.c", depth: 0,
      note: { th: "6 element (`NO SO WE EA F C`) ต้องครบและห้ามซ้ำ แล้วทุกอย่างหลังจากนั้นคือแผนที่ — บรรทัดว่างกลางแผนที่ถือว่าผิด",
              en: "All six elements (`NO SO WE EA F C`) must appear exactly once; everything after them is the map — and a blank line inside the map is an error." },
      data: "NO ./north.xpm ... F 220,100,0   C 30,60,120",
      vars: [ { n: "map", v: "char **", d: { th: "เก็บเป็น array ของ string ก่อน ค่อย validate", en: "stored as an array of strings first, validated after" }, w: true } ] },
    { fn: "validate_map()", file: "validate.c", depth: 1,
      note: { th: "ตรวจว่าปิดสนิทด้วย flood fill จากช่องเดินได้ทุกช่อง ถ้าไหลออกนอกขอบหรือชนช่องว่างแปลว่าแผนที่รั่ว — และผู้เล่นต้องมีตัวเดียวเท่านั้น",
              en: "Flood-fill from every walkable cell: leaking off the edge or reaching a space means the map is open — and there must be exactly one player." },
      data: "ผู้เล่น 'N' ที่ (3,5)  ->  dir = (0,-1), plane = (0.66, 0)",
      vars: [ { n: "player.dir", v: "(0,-1)", d: { th: "ทิศหันหน้า แปลงจากตัวอักษร N/S/E/W", en: "facing direction, derived from the N/S/E/W letter" }, w: true } ] },
    { fn: "render_frame() — ต่อ 1 คอลัมน์", file: "raycast.c", depth: 0,
      note: { th: "**1 ray ต่อ 1 คอลัมน์จอ** ไม่ใช่ต่อ pixel — `cameraX` ไล่จาก -1 ถึง 1 ตลอดความกว้างจอ แล้วทิศ ray = `dir + plane * cameraX`",
              en: "**One ray per screen column**, not per pixel: `cameraX` sweeps from -1 to 1 across the screen and the ray direction is `dir + plane * cameraX`." },
      data: "x = 640/1280  ->  cameraX = 0.0  ->  rayDir = dir",
      vars: [ { n: "cameraX", v: "0.0", d: { th: "0 คือกลางจอ, ±1 คือขอบซ้าย/ขวา", en: "0 is screen centre, ±1 the left and right edges" } } ] },
    { fn: "dda_step()", file: "raycast.c", depth: 1,
      note: { th: "เดินทีละ **ช่องตาราง** ไม่ใช่ทีละหน่วยเล็ก ๆ: ทุกรอบเลือกก้าวแกน x หรือ y ตามว่า `sideDistX` กับ `sideDistY` อันไหนน้อยกว่า จึงไม่มีวันพลาดผนัง",
              en: "Step a whole **grid cell** at a time rather than in tiny increments: each round advance on x or y depending on which of `sideDistX` and `sideDistY` is smaller, so a wall can never be missed." },
      data: "step 1: mapX=4  step 2: mapY=4  ...  ชนที่ (7,5) side=0",
      vars: [ { n: "side", v: "0", d: { th: "0 = ชนด้านแนวตั้ง (EA/WE), 1 = แนวนอน (NO/SO)", en: "0 means a vertical wall (EA/WE), 1 a horizontal one (NO/SO)" }, w: true } ] },
    { fn: "perp_wall_dist()", file: "raycast.c", depth: 1,
      note: { th: "ต้องใช้ระยะ **ตั้งฉากกับระนาบกล้อง** ไม่ใช่ระยะยุคลิดจากผู้เล่น — ใช้ระยะตรง ๆ เมื่อไรผนังจะโค้งเป็น fisheye ทันที",
              en: "Use the distance **perpendicular to the camera plane**, not the Euclidean distance from the player — the straight distance is exactly what bends the walls into a fisheye." },
      data: "perpDist = 4.31  ->  lineHeight = WIN_H / 4.31 = 167 px",
      vars: [ { n: "lineHeight", v: "167", d: { th: "ใกล้ = สูง, ไกล = เตี้ย", en: "near is tall, far is short" }, w: true } ] },
    { fn: "pick_texture()", file: "texture.c", depth: 1,
      note: { th: "เลือก texture จาก `side` บวกทิศของ ray (4 กรณี) แล้วหา `wallX` = จุดที่ ray ชนบนหน้าผนัง เพื่อแปลงเป็นคอลัมน์ของ texture",
              en: "Pick the texture from `side` plus the ray's direction (four cases), then compute `wallX`, the point along the wall face that was hit, and turn it into a texture column." },
      data: "side=0, rayDirX>0  ->  EA   wallX=0.37  ->  texX = 0.37*64 = 23",
      vars: [ { n: "texX", v: "23", d: { th: "บางกรณีต้องพลิกซ้าย-ขวา ไม่งั้น texture กลับด้าน", en: "some cases must be mirrored or the texture comes out reversed" }, w: true } ] },
    { fn: "draw_column()", file: "draw.c", depth: 1,
      note: { th: "ไล่ y จากบนลงล่างของแถบผนัง แล้วสุ่มแถวของ texture ด้วย `texPos` ที่เพิ่มทีละ `step` — ส่วนบนเป็นเพดาน ส่วนล่างเป็นพื้น เติมสีล้วน",
              en: "Walk y down the wall strip sampling texture rows with `texPos`, advanced by `step` each row; above it is the ceiling colour and below it the floor colour." },
      data: "y 276..443 = ผนัง · 0..275 = เพดาน · 444..719 = พื้น",
      vars: [ { n: "img.addr", d: { th: "เขียนลง buffer เดียว ไม่เรียก mlx ทีละ pixel", en: "one buffer; never call mlx per pixel" }, w: true } ] },
    { fn: "move_player()", file: "move.c", depth: 0,
      note: { th: "เดินแล้วต้องเช็คชนผนัง **แยกแกน x กับ y** ไม่งั้นเดินเฉียงชนมุมแล้วค้างสนิท; หมุนใช้เมทริกซ์หมุนกับทั้ง `dir` และ `plane` พร้อมกัน",
              en: "Collision must be tested **per axis**, or moving diagonally into a corner locks you solid; rotation applies the same matrix to both `dir` and `plane`." },
      data: "W: pos.x += dir.x * 0.05  ถ้า map[y][newX] != '1'",
      vars: [ { n: "pos", v: "(3.05, 5.0)", d: { th: "เก็บเป็นทศนิยม ไม่ใช่ช่องตาราง", en: "kept as floats, not grid cells" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.ai_finetune = {
  input: "งาน: จัดหมวดอีเมลลูกค้า 9 ประเภท — prompt ยาวขึ้นเรื่อย ๆ แต่ยังพลาด",
  steps: [
    { fn: "ไต่บันไดจากล่างขึ้นบน", file: "decision", depth: 0,
      note: { th: "ลำดับที่ถูกคือ **prompt → few-shot → RAG → fine-tune** เพราะสามขั้นแรกแก้ได้ในไม่กี่นาทีและย้อนกลับได้ ส่วน fine-tune ผูกคุณเข้ากับ pipeline ที่ต้องดูแลตลอด",
              en: "The right order is **prompt → few-shot → RAG → fine-tune**, because the first three take minutes and are reversible, while fine-tuning commits you to a pipeline you have to maintain." },
      data: "prompt เดี่ยว 71% · few-shot 78% · RAG 79% · ต้องการ 90%",
      vars: [ { n: "ceiling", v: "79%", d: { th: "เพดานของวิธีที่ไม่ต้องเทรน", en: "the ceiling of the training-free approaches" }, w: true } ] },
    { fn: "fine-tune แก้อะไรได้จริง", file: "scoping", depth: 1,
      note: { th: "มันสอน **พฤติกรรมและรูปแบบ** ไม่ใช่ **ข้อเท็จจริง** — อยากให้รู้ข้อมูลใหม่ต้องใช้ RAG; อยากให้ตอบสั้น ตรงฟอร์แมต ตรงโทน ทุกครั้ง ค่อยเทรน",
              en: "Training installs **behaviour and format**, not **facts** — new knowledge belongs in RAG; consistent brevity, format and tone are what training is for." },
      data: "เป้าหมาย: ตอบเป็น label เดียวเสมอ, ไม่มีคำอธิบายพ่วง",
      vars: [ { n: "task_type", v: "classification", d: { th: "งานคงที่ ปริมาณสูง = คุ้มเทรนที่สุด", en: "a stable, high-volume task is where training pays best" } } ] },
    { fn: "สร้างชุดข้อมูล", file: "data/train.jsonl", depth: 1,
      note: { th: "**คุณภาพชนะปริมาณ** 500 ตัวอย่างที่สะอาดดีกว่า 50,000 ตัวอย่างที่ปนขยะ และต้องใช้ **chat template ตัวเดียวกับตอน inference เป๊ะ** ไม่งั้นโมเดลเรียนรูปแบบที่ไม่มีวันเจอจริง",
              en: "**Quality beats quantity** — 500 clean examples beat 50,000 noisy ones — and the **chat template must match inference exactly**, or the model learns a format it will never see again." },
      data: "1,200 ตัวอย่าง · แบ่ง train/val/test 80/10/10 · dedupe แล้ว",
      vars: [ { n: "loss mask", d: { th: "คิด loss เฉพาะส่วนคำตอบ ไม่ใช่ทั้ง prompt", en: "compute loss on the answer only, never on the prompt" }, w: true } ] },
    { fn: "LoRA: ΔW = B · A", file: "train.py", depth: 1,
      note: { th: "แทนที่จะขยับน้ำหนักทั้งก้อน เพิ่มส่วนต่างอันดับต่ำเข้าไป: `A` สุ่มค่าเริ่มต้น ส่วน `B` **เริ่มที่ศูนย์** โมเดลตอนเริ่มเทรนจึงเท่ากับตัวเดิมเป๊ะ",
              en: "Instead of moving the whole weight matrix, add a low-rank delta: `A` is randomly initialised while `B` **starts at zero**, so at step 0 the model is bit-for-bit the original." },
      data: "r=16  alpha=32  target: q_proj,k_proj,v_proj,o_proj",
      vars: [ { n: "trainable", v: "0.4% ของพารามิเตอร์", d: { th: "คอขวดอันดับ r บังคับให้เรียนรูปแบบ ไม่ใช่ท่องจำ", en: "the rank bottleneck forces pattern learning over memorisation" }, w: true } ] },
    { fn: "เทรน + ดู loss", file: "train.py", depth: 2,
      note: { th: "**loss ลงไม่ได้แปลว่าดีขึ้น** — มันวัดว่าทายโทเค็นถัดไปแม่นแค่ไหน ไม่ได้วัดว่างานถูก วัดด้วย metric ของงานจริงทุก checkpoint",
              en: "**Falling loss is not improvement** — it measures next-token accuracy, not task correctness. Score the real task metric at every checkpoint." },
      data: "epoch 1: loss 0.62 acc 86% · epoch 3: loss 0.31 acc 84% (แย่ลง)",
      vars: [ { n: "epochs", v: "2", d: { th: "เกิน 2-3 epoch มักเริ่ม overfit ในชุดเล็ก", en: "past two or three epochs a small set usually overfits" }, w: true } ] },
    { fn: "ประเมิน 3 ทาง", file: "eval.py", depth: 1,
      note: { th: "เทียบ **โมเดลเดิม + prompt เดิม**, **โมเดลเดิม + prompt ที่ดีที่สุด** และ **โมเดลที่เทรนแล้ว** บนชุด test เดียวกัน — ถ้าไม่มีคอลัมน์กลาง คุณจะไม่มีวันรู้ว่าเทรนคุ้มจริงไหม",
              en: "Compare **base with the old prompt**, **base with your best prompt** and **the tuned model** on one held-out set — without the middle column you can never tell whether training was worth it." },
      data: "base 71% · best-prompt 79% · tuned 91%   (+12 จุดจากการเทรน)",
      vars: [ { n: "regression check", d: { th: "ต้องเช็คงานอื่นด้วย กัน catastrophic forgetting", en: "check unrelated tasks too, to catch catastrophic forgetting" }, w: true } ] },
    { fn: "คิดจุดคุ้มทุน", file: "napkin math", depth: 1,
      note: { th: "เทรนไม่ได้ฟรี: ค่าเทรน + ค่า host adapter + เวลาที่ต้องเทรนใหม่ทุกครั้งที่ base model ขยับ เทียบกับ token ที่ประหยัดได้จาก prompt ที่สั้นลง",
              en: "Training is not free: training cost, adapter hosting, and re-training every time the base model moves, weighed against the tokens a shorter prompt saves." },
      data: "prompt สั้นลง 1,800 token/call × 40k call/เดือน  ->  คืนทุนใน 3 สัปดาห์",
      vars: [ { n: "verdict", v: "ทำ", d: { th: "งานคงที่ ปริมาณสูง prompt ยาว = เคสที่คุ้ม", en: "stable, high-volume, long-prompt work is the case that pays" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.ai_output_control = {
  input: "ต้องการ JSON ล้วน แต่โมเดลตอบ \"Sure! Here is the JSON:\" ```json ...```",
  steps: [
    { fn: "log สตริงสุดท้ายที่ส่งจริง", file: "debug", depth: 0,
      note: { th: "ก่อนโทษโมเดล ให้พิมพ์ prompt **หลัง templating** ออกมาดูก่อน — รายงานส่วนใหญ่ที่ว่า 'โมเดลไม่ทำตามคำสั่ง' คือบั๊กของการประกอบ template",
              en: "Before blaming the model, print the prompt **after templating** — most 'the model ignores my instruction' reports are a templating bug." },
      data: "พบว่า {{format_rules}} ไม่ถูกแทนค่า ส่งไปเป็นตัวอักษรดิบ",
      vars: [ { n: "final_prompt", d: { th: "สิ่งที่ API เห็นจริง ไม่ใช่สิ่งที่เราคิดว่าส่ง", en: "what the API actually saw, not what you think you sent" }, w: true } ] },
    { fn: "ทำให้ผลลัพธ์ผิดเป็นไปไม่ได้", file: "structured output", depth: 0,
      note: { th: "constrained decoding **มาสก์โทเค็นที่จะทำให้ผิด schema ทิ้ง** ผลลัพธ์ที่ผิดจึงไม่ใช่แค่ 'ไม่แนะนำ' แต่ผลิตไม่ได้เลย — แรงกว่าการขอด้วยคำพูดทุกแบบ",
              en: "Constrained decoding **masks out any token that would break the schema**, so invalid output is not discouraged, it is impossible — stronger than any wording." },
      data: "schema: {reason: string, label: enum[9 ค่า]}",
      vars: [ { n: "field order", d: { th: "วางช่องเหตุผล **ก่อน** ข้อสรุป โมเดลจึงคิดก่อนตอบ", en: "put the reasoning field **before** the conclusion so the model thinks first" }, w: true } ] },
    { fn: "prefill ช่องผู้ช่วย", file: "messages[]", depth: 1,
      note: { th: "ใส่ต้นคำตอบลงใน assistant turn เอง โมเดลต้องเขียนต่อจากตรงนั้น **ช่องสำหรับคำนำหายไปเลย** และอย่าลืมว่า prefill ไม่ได้อยู่ใน response ต้องเอามาต่อหน้าเอง",
              en: "Put the opening of the answer in the assistant turn; the model must continue from there and **the preamble slot is simply gone**. Remember the prefill is not in the response — prepend it yourself." },
      data: "{\"role\": \"assistant\", \"content\": \"{\"}",
      vars: [ { n: "preamble", v: "ตายแล้ว", d: { th: "ไม่มี 'Sure! Here is' และไม่มี code fence", en: "no 'Sure! Here is' and no markdown fence" }, w: true } ] },
    { fn: "stop sequence", file: "params", depth: 1,
      note: { th: "หยุดทันทีที่เจอสตริงที่กำหนด และสตริงนั้นไม่ถูกส่งกลับมาด้วย — จับคู่กับ prefill ได้กรอบเป๊ะ: prefill `<answer>` แล้ว stop ที่ `</answer>`",
              en: "Generation halts the moment the sequence appears and the sequence is not returned — pair it with prefill for an exact frame: prefill `<answer>`, stop at `</answer>`." },
      data: "stop_sequences: [\"</answer>\", \"\\n\\nHuman:\"]",
      vars: [ { n: "max_tokens", d: { th: "ยังต้องมีเป็นตาข่ายกันตก stop ไม่ได้ตัดกลางคัน", en: "still needed as a backstop; stop sequences do not truncate" } } ] },
    { fn: "จัดโครง prompt", file: "prompt", depth: 1,
      note: { th: "โมเดลมองไม่เห็นเครื่องหมายคำพูดของเรา — คั่นด้วยแท็กแบบ XML แล้ววางคำสั่งที่ไม่เปลี่ยน **ไว้บนสุด** (cache ดี) ข้อมูลที่เปลี่ยนไว้ล่าง",
              en: "The model cannot see your quotes: delimit with XML-style tags, put durable instructions **first** (they cache well) and the variable data last." },
      data: "<instructions>...</instructions>\\n<document>{{user_text}}</document>",
      vars: [ { n: "injection", d: { th: "'ignore previous instructions' ตอนนี้อยู่ใน <document> อย่างเห็นได้ชัด", en: "'ignore previous instructions' now sits visibly inside <document>" }, w: true } ] },
    { fn: "สั่งเชิงบวก ไม่ใช่เชิงลบ", file: "prompt", depth: 2,
      note: { th: "`ตอบเป็น JSON เท่านั้น` ได้ผลกว่า `ห้ามใส่คำอธิบาย` เพราะการห้ามต้องบรรยายสิ่งที่ห้ามอย่างละเอียด ซึ่งทำให้สิ่งนั้นยังอยู่ใน context",
              en: "'Reply with JSON only' outperforms 'do not add explanations', because a negation describes the forbidden output in detail and keeps it present in context." },
      data: "และขอหน่วยที่นับได้: 'สามบูลเล็ต' ไม่ใช่ 'สั้น ๆ'",
      vars: [ { n: "few-shot", v: "2 ตัวอย่าง", d: { th: "ตัวอย่างในรูปแบบเป้าหมายคือการคุมฟอร์แมตที่ดีที่สุด", en: "two examples in the exact target shape are the best format control" } } ] },
    { fn: "แตะ sampling เป็นอันดับสุดท้าย", file: "params", depth: 1,
      note: { th: "ปรับ **ตัวเดียว**: ลดทั้ง temperature และ top_p พร้อมกันจะกลายเป็น greedy แล้ววนซ้ำ และ **temperature 0 ไม่ใช่ determinism** — batching, float ที่บวกไม่สลับที่บน GPU, การ route ของ MoE และเวอร์ชันโมเดล ล้วนทำให้ผลเปลี่ยน",
              en: "Tune **one**: lowering temperature and top_p together compounds into near-greedy output that loops — and **temperature 0 is not determinism**, since batching, non-associative float on GPUs, MoE routing and model updates all move the output." },
      data: "temperature=0 สำหรับ extraction · 0.7-1.0 สำหรับงานเขียน",
      vars: [ { n: "reproducibility", d: { th: "ถ้าต้องการซ้ำได้จริง ให้ cache คำตอบและ pin เวอร์ชันโมเดล", en: "if you need reproducibility, cache the response and pin the model version" }, w: true } ] },
    { fn: "validate แล้วซ่อมหนึ่งรอบ", file: "call.py", depth: 0,
      note: { th: "validation เป็นส่วนหนึ่งของการเรียก ไม่ใช่ของแถม: ป้อน **ข้อความ error ของ validator** กลับไป (ไม่ใช่แค่ 'ผิดนะ') แล้ว **ซ่อมรอบเดียว** ก่อน fallback — ลูปที่ซ่อมจนกว่าจะสำเร็จคือบิลที่ไม่มีเพดาน",
              en: "Validation is part of the call, not an afterthought: feed the **validator's own message** back (not 'that was wrong'), allow **one** repair round, then fall back — a loop that repairs until success is an unbounded bill." },
      data: "ValidationError: label must be one of [...]  ->  retry 1 ครั้ง  ->  ผ่าน",
      vars: [ { n: "repair_rate", d: { th: "นับไว้เป็น metric — ค่าที่ค่อย ๆ สูงขึ้นแปลว่า prompt/schema/โมเดลเริ่มเพี้ยน", en: "track it as a metric; a rising rate means a prompt, schema or model version has drifted" }, w: true } ] }
  ]
};
