/* ============================================================
   data.flows2.js — flow visualizer สำหรับสาย core (libft, ft_printf,
   get_next_line) และ CPP Module 01-09
   โครงเดียวกับ FLOWS ใน app.js: { input, steps:[{fn,file,depth,note,data,vars}] }
   ============================================================ */
window.EXTRA_FLOWS = window.EXTRA_FLOWS || {};

window.EXTRA_FLOWS.libft = {
  input: "ft_split(\"  42  is  fun \", ' ')",
  steps: [
    { fn: "ft_split(s, c)", file: "ft_split.c", depth: 0,
      note: { th: "คืน **array ของ string ที่จบด้วย NULL** ผู้เรียกจึงวนอ่านได้โดยไม่ต้องรู้จำนวน — และเป็นเจ้าของหน่วยความจำทั้งก้อนต่อจากนี้",
              en: "Returns a **NULL-terminated array of strings**, so the caller can walk it without knowing the count — and owns every allocation from here on." },
      data: "s = \"  42  is  fun \"   c = ' '",
      vars: [ { n: "s", v: "\"  42  is  fun \"", d: { th: "ตัวคั่นติดกันหลายตัวและมีที่หัวท้ายด้วย", en: "separators repeat, and appear at both ends" } } ] },
    { fn: "count_words(s, c)", file: "ft_split.c", depth: 1,
      note: { th: "นับคำก่อนจองหน่วยความจำ เพราะต้องรู้ขนาด array ล่วงหน้า — เงื่อนไขคือ 'ตัวนี้ไม่ใช่ตัวคั่น และตัวก่อนหน้าเป็นตัวคั่นหรือเป็นต้นสตริง'",
              en: "Count first, because the array size must be known before allocating — a word starts where 'this character is not the separator and the previous one was, or this is the start'." },
      data: "\"42\", \"is\", \"fun\"  ->  3",
      vars: [ { n: "words", v: "3", d: { th: "ตัวคั่นซ้อนกันต้องไม่ถูกนับเป็นคำว่าง", en: "repeated separators must not count as empty words" }, w: true } ] },
    { fn: "malloc((words + 1) * sizeof(char *))", file: "ft_split.c", depth: 1,
      note: { th: "**+1 คือช่องสำหรับ NULL ปิดท้าย** ลืมช่องนี้แล้วผู้เรียกจะวนเลยขอบ array ไปอ่านหน่วยความจำที่ไม่ใช่ของตัวเอง",
              en: "**The +1 is the slot for the terminating NULL.** Forget it and the caller walks past the end into memory that is not theirs." },
      data: "tab = malloc(4 * 8) = 32 bytes",
      vars: [ { n: "tab", d: { th: "ต้องเช็ค NULL ทันที — malloc ล้มเหลวได้เสมอ", en: "check for NULL immediately; malloc can always fail" }, w: true } ] },
    { fn: "ft_substr(s, start, len)", file: "ft_substr.c", depth: 2,
      note: { th: "แต่ละคำถูกคัดลอกออกมาเป็นสตริงใหม่ที่จองแยก — split จึงไม่ผูกกับอายุของ `s` ผู้เรียกจะ free `s` ทิ้งได้ทันที",
              en: "Each word is copied into its own allocation, so the result does not depend on the lifetime of `s` — the caller may free `s` straight away." },
      data: "substr(s, 2, 2) -> \"42\"",
      vars: [ { n: "tab[0]", v: "\"42\"", d: { th: "สตริงใหม่ที่จบด้วย '\\0' ของตัวเอง", en: "a fresh string with its own terminating '\\0'" }, w: true } ] },
    { fn: "ถ้า malloc กลางทางล้มเหลว", file: "ft_split.c", depth: 2,
      note: { th: "ต้อง **free ทุกคำที่จองไปแล้ว** และ free ตัว array ก่อนคืน NULL — ไม่ใช่แค่ return NULL เฉย ๆ ไม่งั้นคือ leak ที่ valgrind จับได้ทันที",
              en: "You must **free every word already allocated** and the array itself before returning NULL — simply returning NULL is a leak valgrind catches at once." },
      data: "free(tab[0]); free(tab[1]); free(tab); return (NULL);",
      vars: [ { n: "i", d: { th: "ตัวนับที่บอกว่าจองสำเร็จไปกี่ตัวแล้ว", en: "the counter telling you how many succeeded" } } ] },
    { fn: "tab[words] = NULL", file: "ft_split.c", depth: 1,
      note: { th: "จุดปิดสัญญา: ผู้เรียกจะวนด้วย `while (tab[i])` ได้อย่างปลอดภัย นี่คือรูปแบบเดียวกับที่ `argv` และ `envp` ใช้",
              en: "This closes the contract: the caller can safely loop with `while (tab[i])`. It is the same shape `argv` and `envp` use." },
      data: "tab = [\"42\", \"is\", \"fun\", NULL]",
      vars: [ { n: "tab[3]", v: "NULL", d: { th: "ตัวปิด array ไม่ใช่คำ", en: "the array terminator, not a word" }, w: true } ] },
    { fn: "ผู้เรียกต้อง free ให้ครบ", file: "main.c", depth: 0,
      note: { th: "หนึ่ง `ft_split` = **การจอง 1 + จำนวนคำ ครั้ง** ต้อง free ทีละคำแล้วค่อย free ตัว array — free แค่ `tab` คือ leak ทุกคำที่อยู่ข้างใน",
              en: "One `ft_split` is **one allocation plus one per word**. Free each word, then the array — freeing only `tab` leaks every string inside it." },
      data: "while (tab[i]) free(tab[i++]);  free(tab);",
      vars: [ { n: "leak", v: "0", d: { th: "valgrind ต้องบอก all heap blocks were freed", en: "valgrind must report all heap blocks were freed" }, w: true } ] },
    { fn: "ft_lstmap — รูปแบบเดียวกันบน linked list", file: "ft_lstmap.c", depth: 0,
      note: { th: "list ก็ใช้กติกาเดียวกัน: สร้าง node ใหม่ทีละตัว ถ้าตัวไหนล้มเหลวต้อง `ft_lstclear` ส่วนที่สร้างไปแล้วด้วย `del` แล้วคืน NULL",
              en: "The list version follows the same rule: build node by node, and if one fails, `ft_lstclear` what exists so far with `del` and return NULL." },
      data: "new = ft_lstnew(f(lst->content));  if (!new) { ft_lstclear(&head, del); return (NULL); }",
      vars: [ { n: "del", d: { th: "ผู้เรียกเป็นคนบอกวิธี free เนื้อหา เพราะ libft ไม่รู้ว่าข้างในคืออะไร", en: "the caller supplies how to free the content, because libft cannot know what it is" } } ] }
  ]
};

window.EXTRA_FLOWS.ft_printf = {
  input: "ft_printf(\"id=%d name=%s\\n\", 42, \"wiaon-in\")",
  steps: [
    { fn: "ft_printf(fmt, ...)", file: "ft_printf.c", depth: 0,
      note: { th: "รับพารามิเตอร์ไม่จำกัดจำนวนด้วย **variadic** — คอมไพเลอร์ไม่ตรวจชนิดให้ ตัวฟังก์ชันจึงต้องเชื่อ format string ล้วน ๆ ว่าจะดึงอะไรออกมา",
              en: "Takes an unbounded argument list through **variadics** — the compiler checks nothing, so the function trusts the format string alone to know what to pull." },
      data: "fmt = \"id=%d name=%s\\n\"",
      vars: [ { n: "count", v: "0", d: { th: "ตัวนับ byte ที่เขียนออกไป คือค่าที่ต้องคืน", en: "the byte counter that becomes the return value" }, w: true } ] },
    { fn: "va_start(ap, fmt)", file: "ft_printf.c", depth: 1,
      note: { th: "ผูก `ap` ไว้กับตำแหน่งถัดจากพารามิเตอร์สุดท้ายที่มีชื่อ — เพราะแบบนี้จึงต้องมีพารามิเตอร์ที่มีชื่ออย่างน้อยหนึ่งตัวเสมอ",
              en: "Anchors `ap` just past the last **named** parameter — which is exactly why a variadic function must always have at least one named parameter." },
      data: "ap -> [42, \"wiaon-in\"]",
      vars: [ { n: "ap", v: "va_list", d: { th: "เคอร์เซอร์ที่เดินไปข้างหน้าอย่างเดียว ย้อนกลับไม่ได้", en: "a cursor that only moves forward and never back" }, w: true } ] },
    { fn: "เดิน fmt หาตัว '%'", file: "ft_printf.c", depth: 1,
      note: { th: "ตัวอักษรธรรมดาพิมพ์ออกตรง ๆ เจอ `%` ค่อยดูตัวถัดไปว่าเป็น conversion อะไร และ `%%` คือกรณีพิเศษที่ไม่กิน argument",
              en: "Plain characters go straight out; a `%` makes the next character a conversion, and `%%` is the special case that consumes no argument." },
      data: "'i','d','='  พิมพ์ออกไป 3 ตัว  ->  เจอ '%d'",
      vars: [ { n: "count", v: "3", d: { th: "นับทุก byte ที่ write สำเร็จ", en: "counts every byte successfully written" }, w: true } ] },
    { fn: "va_arg(ap, int)  สำหรับ %d", file: "put_nbr.c", depth: 2,
      note: { th: "**ต้องบอกชนิดให้ตรง** เพราะ `va_arg` แค่ขยับเคอร์เซอร์ตามขนาดของชนิดที่บอก บอกผิดชนิดเมื่อไหร่ argument ตัวถัดไปจะเพี้ยนตามกันทั้งแถว",
              en: "**The type must be right**: `va_arg` merely advances the cursor by that type's size, so one wrong type corrupts every argument after it." },
      data: "va_arg(ap, int) -> 42",
      vars: [ { n: "ap", d: { th: "ขยับไปชี้ที่ \"wiaon-in\" แล้ว", en: "now points at \"wiaon-in\"" }, w: true } ] },
    { fn: "default argument promotion", file: "ft_printf.c", depth: 2,
      note: { th: "`char` และ `short` ถูก **เลื่อนขึ้นเป็น `int`** ก่อนถูกส่งเข้าฟังก์ชัน variadic เสมอ — `%c` จึงต้องรับด้วย `va_arg(ap, int)` ไม่ใช่ `char` และ `float` ถูกเลื่อนเป็น `double`",
              en: "`char` and `short` are **promoted to `int`** before entering a variadic call — so `%c` must be read as `va_arg(ap, int)`, never `char`, and a `float` arrives as a `double`." },
      data: "%c -> va_arg(ap, int) แล้วค่อย cast เป็น char",
      vars: [ { n: "promotion", d: { th: "กฎของภาษา ไม่ใช่ทางเลือกของเรา", en: "a language rule, not a choice" } } ] },
    { fn: "ft_putnbr_fd แบบ recursive", file: "put_nbr.c", depth: 3,
      note: { th: "หารสิบไปเรื่อยแล้วพิมพ์ตอนคลายกลับ ตัวเลขจึงออกมาเรียงถูกลำดับ — และต้องรับมือ `INT_MIN` ที่ `-n` ล้นขอบเขต",
              en: "Divide by ten and print on the way back up so the digits come out in order — and handle `INT_MIN`, whose `-n` overflows." },
      data: "42 -> putnbr(4) then putchar('2')  ->  \"42\"",
      vars: [ { n: "count", v: "5", d: { th: "3 + 2 byte ของเลข", en: "3 plus the 2 digits" }, w: true } ] },
    { fn: "%s กับ NULL", file: "put_str.c", depth: 2,
      note: { th: "`ft_printf(\"%s\", NULL)` ต้องพิมพ์ `(null)` ไม่ใช่ crash — printf จริงทำแบบนี้ และ moulinette เทสต์เคสนี้ตรง ๆ",
              en: "`ft_printf(\"%s\", NULL)` must print `(null)` rather than crash — the real printf does, and moulinette tests it directly." },
      data: "va_arg(ap, char *) -> \"wiaon-in\"  (8 byte)",
      vars: [ { n: "count", v: "19", d: { th: "สะสมไปเรื่อยจนจบ format", en: "accumulates to the end of the format" }, w: true } ] },
    { fn: "va_end(ap) แล้ว return count", file: "ft_printf.c", depth: 0,
      note: { th: "`va_end` เป็นข้อบังคับของมาตรฐาน และค่าที่คืนคือ **จำนวน byte ที่เขียนจริง** ไม่ใช่จำนวน argument — เขียนไม่สำเร็จควรคืน -1",
              en: "`va_end` is required by the standard, and the return value is **the number of bytes actually written**, not the number of arguments — a failed write should return -1." },
      data: "\"id=42 name=wiaon-in\\n\"  ->  return 20",
      vars: [ { n: "return", v: "20", d: { th: "นับ '\\n' ด้วย", en: "the '\\n' counts too" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.get_next_line = {
  input: "อ่านไฟล์ 3 บรรทัดด้วย BUFFER_SIZE=4",
  steps: [
    { fn: "get_next_line(fd)", file: "get_next_line.c", depth: 0,
      note: { th: "สัญญาคือ **คืนหนึ่งบรรทัดรวม `\\n` ต่อการเรียกหนึ่งครั้ง** และคืน NULL เมื่อหมดไฟล์ — ผู้เรียกเป็นเจ้าของสตริงที่ได้และต้อง free เอง",
              en: "The contract is **one line per call, including the `\\n`**, and NULL at end of file — the caller owns the returned string and must free it." },
      data: "ไฟล์: \"ab\\ncdef\\ngh\"   BUFFER_SIZE = 4",
      vars: [ { n: "fd", v: "3", d: { th: "ใช้เป็นดัชนีของ stash ในเวอร์ชัน bonus", en: "used as the stash index in the bonus version" } } ] },
    { fn: "static char *stash[FD_MAX]", file: "get_next_line.c", depth: 1,
      note: { th: "**`static` คือหัวใจของโจทย์นี้** — ตัวแปรอยู่รอดข้ามการเรียก จึงจำสิ่งที่อ่านเกินมาจากรอบก่อนได้ ถ้าเป็นตัวแปรปกติข้อมูลจะหายทุกครั้งที่ฟังก์ชันจบ",
              en: "**`static` is the whole point**: the variable survives between calls, so it remembers what the previous call over-read. An ordinary local would lose it every time the function returns." },
      data: "stash[3] = NULL  (เรียกครั้งแรก)",
      vars: [ { n: "stash[3]", d: { th: "ส่วนที่เหลือค้างจากรอบก่อน", en: "the leftover from the previous call" }, w: true } ] },
    { fn: "read(fd, buf, BUFFER_SIZE)", file: "get_next_line.c", depth: 2,
      note: { th: "ค่าคืนมีความหมาย **3 แบบ**: มากกว่า 0 คือได้ข้อมูลมาเท่านั้น byte, เท่ากับ 0 คือจบไฟล์, น้อยกว่า 0 คือ error — ต้องแยกทั้งสามกรณี ไม่ใช่แค่เช็ค `> 0`",
              en: "The return value has **three meanings**: greater than zero is that many bytes, zero is end of file, negative is an error — all three need handling, not just a `> 0` check." },
      data: "read -> 4  buf = \"ab\\ncd\"",
      vars: [ { n: "n", v: "4", d: { th: "buf ไม่ได้จบด้วย '\\0' เอง ต้องปิดเอง", en: "buf is not null-terminated by read; you must do it" }, w: true } ] },
    { fn: "ต่อ buf เข้ากับ stash", file: "get_next_line_utils.c", depth: 2,
      note: { th: "`ft_strjoin` สร้างสตริงใหม่ทุกครั้ง จึงต้อง **free ตัวเก่าทันที** ไม่งั้นทุกการวนซ้ำคือหนึ่ง leak — นี่คือจุดที่ leak เกิดบ่อยที่สุดของโปรเจกต์นี้",
              en: "`ft_strjoin` allocates a new string every time, so **free the old one immediately** or every iteration leaks — this is where the project leaks most often." },
      data: "stash = \"ab\\ncd\"   (ยังไม่มี \\n? มี -> หยุดอ่าน)",
      vars: [ { n: "stash", v: "\"ab\\ncd\"", d: { th: "วน read ต่อจนกว่าจะเจอ '\\n' หรือ EOF", en: "keep reading until a '\\n' appears or EOF" }, w: true } ] },
    { fn: "ตัดบรรทัดออกจาก stash", file: "get_next_line.c", depth: 1,
      note: { th: "คัดลอกตั้งแต่ต้นจนถึง `\\n` **รวมตัว `\\n` ด้วย** เป็นค่าที่คืน ส่วนที่เหลือหลัง `\\n` คือ stash รอบถัดไป — บรรทัดสุดท้ายที่ไม่มี `\\n` ก็ต้องคืนได้เหมือนกัน",
              en: "Copy from the start through the `\\n` **including it** as the return value; whatever follows becomes the next stash — and a final line with no `\\n` must still be returned." },
      data: "line = \"ab\\n\"   stash = \"cd\"",
      vars: [ { n: "line", v: "\"ab\\n\"", d: { th: "ผู้เรียกเป็นเจ้าของ ต้อง free", en: "owned by the caller, who must free it" }, w: true },
              { n: "stash", v: "\"cd\"", d: { th: "อ่านเกินมาแล้ว เก็บไว้ใช้รอบหน้า", en: "already read; kept for the next call" }, w: true } ] },
    { fn: "เรียกครั้งที่ 2", file: "get_next_line.c", depth: 0,
      note: { th: "รอบนี้ **เริ่มจาก stash ที่ยังมี `cd` อยู่** แล้วค่อย read เพิ่ม — ถ้าไม่มี static ตรงนี้จะอ่านซ้ำหรืออ่านข้ามไปเลย",
              en: "This call **starts from the stash still holding `cd`** and only then reads more — without the static, it would either re-read or skip." },
      data: "stash \"cd\" + read \"ef\\ng\"  ->  \"cdef\\ng\"",
      vars: [ { n: "line", v: "\"cdef\\n\"", d: { th: "บรรทัดที่คร่อม buffer หลายก้อน", en: "a line spanning several buffers" }, w: true } ] },
    { fn: "EOF: read คืน 0", file: "get_next_line.c", depth: 1,
      note: { th: "ยังมีข้อมูลค้างใน stash ก็ต้องคืนเป็นบรรทัดสุดท้ายก่อน แล้ว **ล้าง stash ให้เป็น NULL** รอบถัดไปจึงคืน NULL ได้อย่างถูกต้อง",
              en: "If the stash still holds data, return it as the last line, then **clear the stash to NULL** so the following call can correctly return NULL." },
      data: "line = \"gh\"   stash = NULL",
      vars: [ { n: "stash[3]", v: "NULL", d: { th: "ล้างแล้ว ไม่มี leak ค้างตอนโปรแกรมจบ", en: "cleared, so nothing leaks when the program ends" }, w: true } ] },
    { fn: "เรียกครั้งที่ 4 -> NULL", file: "get_next_line.c", depth: 0,
      note: { th: "จบไฟล์แล้วและ stash ว่าง จึงคืน NULL — ผู้เรียกใช้เงื่อนไขนี้ปิดลูป และ **ต้องไม่มีอะไรค้างใน heap อีก**",
              en: "End of file with an empty stash returns NULL, which is how the caller ends its loop — and **nothing may remain on the heap**." },
      data: "while ((line = get_next_line(fd))) { ...; free(line); }",
      vars: [ { n: "valgrind", v: "0 leaks", d: { th: "ทั้ง stash และทุก line ถูกปล่อยครบ", en: "the stash and every line have been released" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_01 = {
  input: "Zombie *heap = newZombie(\"Foo\");  randomChump(\"Bar\");",
  steps: [
    { fn: "randomChump(\"Bar\")", file: "randomChump.cpp", depth: 0,
      note: { th: "สร้างบน **stack** — อ็อบเจกต์เกิดตอนประกาศและถูกทำลายอัตโนมัติเมื่อจบ scope ไม่ต้อง delete และลืมไม่ได้เพราะคอมไพเลอร์จัดการให้",
              en: "Created on the **stack**: it is constructed at its declaration and destroyed automatically at the end of scope — no delete, and nothing to forget." },
      data: "Zombie z(\"Bar\");  z.announce();",
      vars: [ { n: "z", d: { th: "อายุผูกกับ scope เท่านั้น", en: "its lifetime is exactly the scope" }, w: true } ] },
    { fn: "จบ scope -> destructor ทำงานเอง", file: "randomChump.cpp", depth: 1,
      note: { th: "นี่คือ **RAII**: ทรัพยากรผูกกับอายุของอ็อบเจกต์ ออกจาก scope เมื่อไหร่ก็คืนทันที แม้จะออกด้วย exception ก็ตาม",
              en: "This is **RAII**: a resource is tied to an object's lifetime and released the moment the scope ends, even if it ends through an exception." },
      data: "\"Bar destroyed\"",
      vars: [ { n: "z", v: "destroyed", d: { th: "อ้างถึงหลังจากนี้คือ undefined behaviour", en: "referring to it after this is undefined behaviour" }, w: true } ] },
    { fn: "newZombie(\"Foo\")", file: "newZombie.cpp", depth: 0,
      note: { th: "สร้างบน **heap** ด้วย `new` — อยู่รอดข้าม scope ได้ จึงคืน pointer ออกไปได้ แต่แลกด้วยการที่ **ผู้รับต้อง delete เอง**",
              en: "Created on the **heap** with `new`, so it outlives the scope and a pointer can be returned — at the price that **somebody must delete it**." },
      data: "return new Zombie(name);",
      vars: [ { n: "heap", v: "Zombie *", d: { th: "ความเป็นเจ้าของถูกโอนออกไปพร้อม pointer", en: "ownership travels out with the pointer" }, w: true } ] },
    { fn: "delete heap", file: "main.cpp", depth: 0,
      note: { th: "`new` คู่กับ `delete` และ `new[]` คู่กับ `delete[]` เท่านั้น — สลับคู่กันคือ undefined behaviour ที่ valgrind รายงานว่า mismatched free",
              en: "`new` pairs with `delete` and `new[]` with `delete[]`, never crossed — mixing them is undefined behaviour that valgrind reports as a mismatched free." },
      data: "delete heap;   // destructor แล้วค่อยคืน memory",
      vars: [ { n: "heap", d: { th: "หลัง delete คือ dangling pointer ห้ามใช้ต่อ", en: "after delete it is a dangling pointer" }, w: true } ] },
    { fn: "reference เทียบกับ pointer", file: "HumanA / HumanB", depth: 0,
      note: { th: "`HumanA` ถือ **reference** เพราะอาวุธต้องมีตั้งแต่สร้างและเปลี่ยนตัวไม่ได้ ส่วน `HumanB` ถือ **pointer** เพราะอาจยังไม่มีอาวุธ — โครงสร้างข้อมูลบอกความหมายไปในตัว",
              en: "`HumanA` holds a **reference** because the weapon must exist at construction and can never be swapped; `HumanB` holds a **pointer** because it may have none — the type states the intent." },
      data: "HumanA(std::string name, Weapon &w);   HumanB(std::string name);",
      vars: [ { n: "Weapon &", d: { th: "ผูกครั้งเดียวตอนสร้าง ห้ามเป็น NULL", en: "bound once at construction and never null" } },
              { n: "Weapon *", d: { th: "เป็น NULL ได้ เปลี่ยนตัวชี้ได้", en: "may be null, and may be re-pointed" } } ] },
    { fn: "setType() ผ่าน reference", file: "Weapon.cpp", depth: 1,
      note: { th: "เพราะ `HumanA` ถือ reference ไม่ใช่สำเนา การเปลี่ยนชนิดอาวุธจากข้างนอกจึงเห็นผลทันทีทั้งสองฝั่ง — ถ้าเก็บเป็นสำเนาจะไม่เกิดผลนี้",
              en: "Because `HumanA` holds a reference rather than a copy, changing the weapon from outside is visible on both sides at once — a copy would not behave this way." },
      data: "club.setType(\"some other type of club\");",
      vars: [ { n: "club", d: { th: "อ็อบเจกต์เดียวกัน ไม่ใช่คนละตัว", en: "the same object, not a second one" }, w: true } ] },
    { fn: "pointer-to-member function", file: "Harl.cpp", depth: 0,
      note: { th: "เก็บ **ที่อยู่ของ method** ไว้ใน array แล้วเรียกผ่านตัวแปร ทำให้แทนที่ if-else ยาว ๆ ด้วยตารางได้ — เพิ่มระดับใหม่ก็แค่เพิ่มแถวในตาราง",
              en: "Store **the address of a method** in an array and call through it, replacing a long if-else chain with a table — a new level is just one more row." },
      data: "void (Harl::*f[4])() = { &Harl::debug, &Harl::info, ... };  (this->*f[i])();",
      vars: [ { n: "f[i]", d: { th: "ต้องใช้ `.*` หรือ `->*` ในการเรียก", en: "called through `.*` or `->*`" } } ] },
    { fn: "std::ifstream + std::ofstream", file: "replace.cpp", depth: 0,
      note: { th: "stream เป็น RAII เช่นกัน — ปิดไฟล์เองตอนออกจาก scope แต่ต้องเช็ค `is_open()` เสมอ เพราะเปิดไม่ได้แล้วเขียนต่อคือความล้มเหลวเงียบ ๆ",
              en: "Streams are RAII too: they close themselves at end of scope. Always check `is_open()`, because writing to a stream that failed to open fails silently." },
      data: "std::ifstream in(file.c_str());   if (!in.is_open()) return 1;",
      vars: [ { n: "in", d: { th: "destructor ปิดให้เอง ไม่ต้องเรียก close()", en: "the destructor closes it; no close() needed" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_02 = {
  input: "Fixed a(5.05f);  Fixed b(2);  std::cout << a * b;",
  steps: [
    { fn: "Fixed(const float f)", file: "Fixed.cpp", depth: 0,
      note: { th: "**fixed point** เก็บทศนิยมด้วยจำนวนเต็มตัวเดียว โดยกันบิตล่างไว้ 8 บิตเป็นเศษ — ค่าจริงคือ `raw / 256`",
              en: "**Fixed point** stores a fraction inside one integer by reserving the low 8 bits — the real value is `raw / 256`." },
      data: "5.05f * 256 = 1292.8  ->  roundf -> 1293",
      vars: [ { n: "_value", v: "1293", d: { th: "ต้อง `roundf` ไม่ใช่ตัดทิ้ง ไม่งั้นค่าจะเบ้ลงเสมอ", en: "use `roundf`, not truncation, or every value skews downward" }, w: true } ] },
    { fn: "Fixed(const int i)", file: "Fixed.cpp", depth: 0,
      note: { th: "constructor คนละตัวสำหรับ `int` — แค่เลื่อนบิตซ้าย 8 ไม่ต้องปัดเศษเพราะไม่มีเศษ นี่คือ **overloading** ที่เลือกให้เองตามชนิด",
              en: "A separate constructor for `int`: shift left by 8, with no rounding because there is no fraction. This is **overloading** resolved by type." },
      data: "2 << 8 = 512",
      vars: [ { n: "_value", v: "512", d: { th: "2.0 ในรูป fixed point", en: "2.0 in fixed point" }, w: true } ] },
    { fn: "Orthodox Canonical Form", file: "Fixed.hpp", depth: 1,
      note: { th: "4 อย่างที่ต้องมีครบ: default constructor, copy constructor, copy assignment operator และ destructor — คลาสที่ถือทรัพยากรและขาดข้อใดข้อหนึ่งจะพังแบบเงียบ ๆ",
              en: "Four members are mandatory: a default constructor, a copy constructor, a copy assignment operator and a destructor — a resource-holding class missing any of them breaks quietly." },
      data: "Fixed(const Fixed &o);  Fixed &operator=(const Fixed &o);",
      vars: [ { n: "operator=", d: { th: "ต้องเช็ค self-assignment และคืน `*this` เพื่อให้ต่อกันได้", en: "must guard self-assignment and return `*this` so it can chain" } } ] },
    { fn: "operator*(const Fixed &r)", file: "Fixed.cpp", depth: 0,
      note: { th: "คูณ raw สองตัวได้เศษซ้อนกันสองชั้น (256×256) จึง **ต้องหารกลับด้วย 256 หนึ่งครั้ง** ไม่งั้นผลใหญ่เกินจริง 256 เท่า",
              en: "Multiplying two raw values squares the scale (256×256), so you must **divide back by 256 once**, or the result is 256 times too large." },
      data: "(1293 * 512) / 256 = 2586",
      vars: [ { n: "_value", v: "2586", d: { th: "ยกขึ้นเป็น long ก่อนคูณ กัน int ล้น", en: "widen to long before multiplying, to avoid overflow" }, w: true } ] },
    { fn: "toFloat()", file: "Fixed.cpp", depth: 1,
      note: { th: "หารกลับด้วย 256 เพื่อกลับเป็นทศนิยม — ความคลาดเคลื่อนที่เห็น (10.1016 ไม่ใช่ 10.1) คือธรรมชาติของ fixed point ที่มีเศษแค่ 8 บิต",
              en: "Divide by 256 to get back a float — the small error (10.1016 rather than 10.1) is inherent to having only 8 fractional bits." },
      data: "2586 / 256.0 = 10.1016",
      vars: [ { n: "float", v: "10.1016", d: { th: "ความละเอียดคือ 1/256 ≈ 0.0039", en: "the resolution is 1/256, about 0.0039" } } ] },
    { fn: "operator<<(ostream &, const Fixed &)", file: "Fixed.cpp", depth: 1,
      note: { th: "ต้องเป็น **ฟังก์ชันอิสระ ไม่ใช่ method** เพราะตัวซ้ายของ `<<` คือ `ostream` ไม่ใช่ `Fixed` — และต้องคืน `ostream &` เพื่อให้ `<<` ต่อกันได้เรื่อย ๆ",
              en: "It must be a **free function, not a method**, because the left operand of `<<` is the `ostream`, not the `Fixed` — and it returns `ostream &` so `<<` can chain." },
      data: "std::cout << a * b  ->  10.1016",
      vars: [ { n: "return", v: "ostream &", d: { th: "คืน reference ไม่ใช่สำเนา", en: "returns the reference, never a copy" } } ] },
    { fn: "operator++ prefix เทียบ postfix", file: "Fixed.cpp", depth: 1,
      note: { th: "prefix คืน **reference** ของตัวเองหลังบวกแล้ว ส่วน postfix ต้องเก็บสำเนาไว้ก่อนบวกแล้วคืน **สำเนา** — postfix จึงแพงกว่าเสมอ และแยกกันด้วยพารามิเตอร์ `int` หลอก",
              en: "Prefix returns a **reference** to itself after incrementing; postfix must copy first and return the **copy** — which is why postfix always costs more. They are told apart by a dummy `int` parameter." },
      data: "Fixed &operator++();      Fixed operator++(int);",
      vars: [ { n: "epsilon", v: "1", d: { th: "หน่วยที่เล็กที่สุดคือ raw บวกหนึ่ง", en: "the smallest step is one raw unit" } } ] },
    { fn: "BSP: จุดอยู่ในสามเหลี่ยมไหม", file: "bsp.cpp", depth: 0,
      note: { th: "ใช้ cross product ของสามด้าน ถ้า **เครื่องหมายเหมือนกันทั้งสาม** แปลว่าจุดอยู่ในสามเหลี่ยม; ถ้ามีตัวใดเป็นศูนย์คือจุดอยู่บนขอบ ซึ่งโจทย์ถือว่า **ไม่นับ**",
              en: "Take the cross product against each edge: **all three signs equal** means inside. A zero means the point lies on an edge, which the subject counts as **outside**." },
      data: "d1, d2, d3 เครื่องหมายเดียวกัน -> true",
      vars: [ { n: "Fixed", d: { th: "ทำได้ทั้งหมดด้วย fixed point ไม่ต้องใช้ float เลย", en: "the whole test runs in fixed point; no float needed" } } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_03 = {
  input: "DiamondTrap diamond(\"Zaz\");  diamond.whoAmI();",
  steps: [
    { fn: "ClapTrap(name)", file: "ClapTrap.cpp", depth: 0,
      note: { th: "constructor ของ **ฐานที่ลึกที่สุดทำงานก่อนเสมอ** — สร้างจากล่างขึ้นบน เพราะคลาสลูกใช้สมาชิกของแม่ได้ตั้งแต่ constructor ของตัวเอง",
              en: "The **deepest base constructs first** — construction runs bottom-up, so a derived class can already use its base's members inside its own constructor." },
      data: "hit=10  energy=10  damage=0",
      vars: [ { n: "_hitPoints", v: "10", d: { th: "ค่าเริ่มต้นของ ClapTrap", en: "ClapTrap's defaults" }, w: true } ] },
    { fn: "ScavTrap(name)", file: "ScavTrap.cpp", depth: 1,
      note: { th: "เรียก constructor ของแม่ผ่าน **initializer list** แล้วค่อยเขียนทับค่าที่ต้องต่าง — ถ้าไปกำหนดใน body จะกลายเป็นการ 'สร้างแล้วแก้' ซึ่งเปลืองและไม่ตรงเจตนา",
              en: "Call the base constructor through the **initializer list**, then overwrite what differs — assigning in the body means constructing and then reassigning, which is wasteful and less clear." },
      data: "ScavTrap::ScavTrap(std::string n) : ClapTrap(n) { _hitPoints = 100; ... }",
      vars: [ { n: "_hitPoints", v: "100", d: { th: "ทับค่าของแม่", en: "overrides the base value" }, w: true } ] },
    { fn: "FragTrap(name)", file: "FragTrap.cpp", depth: 1,
      note: { th: "อีกสาขาหนึ่งที่สืบจาก `ClapTrap` เหมือนกัน — ตรงนี้เองที่ทำให้ DiamondTrap กลายเป็นรูปเพชร และเกิดปัญหา diamond problem",
              en: "The second branch inheriting from the same `ClapTrap` — this is what gives DiamondTrap its diamond shape, and the diamond problem with it." },
      data: "hit=100  energy=100  damage=30",
      vars: [ { n: "_energyPoints", v: "100", d: { th: "ค่าของ FragTrap", en: "FragTrap's values" }, w: true } ] },
    { fn: "DiamondTrap: ClapTrap เกิดกี่ครั้ง", file: "DiamondTrap.cpp", depth: 0,
      note: { th: "สืบจากทั้ง ScavTrap และ FragTrap ที่ต่างก็สืบจาก ClapTrap — โดยปกติ **ClapTrap จะถูกสร้างสองครั้ง** ต้องใช้ `virtual` inheritance ถึงจะเหลือชุดเดียว",
              en: "It inherits from both ScavTrap and FragTrap, which each inherit ClapTrap — by default **ClapTrap is constructed twice**; `virtual` inheritance is what collapses it to one." },
      data: "class ScavTrap : virtual public ClapTrap",
      vars: [ { n: "ambiguity", d: { th: "ไม่มี virtual แล้วเรียก `_hitPoints` จะกำกวมทันที", en: "without virtual, referring to `_hitPoints` is ambiguous" } } ] },
    { fn: "attack(target)", file: "ClapTrap.cpp", depth: 1,
      note: { th: "ต้องเช็ค **พลังชีวิตและพลังงานก่อน** ทุกครั้ง หมดอย่างใดอย่างหนึ่งแล้วทำอะไรไม่ได้ — และการโจมตีหนึ่งครั้งลดพลังงานหนึ่งหน่วยเสมอ",
              en: "Always check **hit points and energy first**: at zero of either, nothing happens — and each attack costs exactly one energy point." },
      data: "if (_hitPoints == 0 || _energyPoints == 0) return;",
      vars: [ { n: "_energyPoints", d: { th: "ลดลงหนึ่งต่อการกระทำหนึ่งครั้ง", en: "decremented once per action" }, w: true } ] },
    { fn: "takeDamage(amount)", file: "ClapTrap.cpp", depth: 1,
      note: { th: "`_hitPoints` เป็น **unsigned** ลบเกินศูนย์แล้วจะวนกลับไปเป็นเลขมหาศาลแทนที่จะติดลบ — ต้องเช็คก่อนลบเสมอ นี่คือกับดักที่ subject วางไว้",
              en: "`_hitPoints` is **unsigned**, so subtracting past zero wraps to a huge number instead of going negative — check before subtracting. This is the trap the subject plants." },
      data: "if (amount >= _hitPoints) _hitPoints = 0; else _hitPoints -= amount;",
      vars: [ { n: "_hitPoints", v: "0", d: { th: "ไม่ใช่ 4294967286", en: "not 4294967286" }, w: true } ] },
    { fn: "whoAmI()", file: "DiamondTrap.cpp", depth: 0,
      note: { th: "ต้องแยกให้ออกว่าอันไหนคือ **ชื่อของ DiamondTrap** และอันไหนคือ `ClapTrap::_name` ที่ถูกตั้งเป็น `<name>_clap_name` — เป็นคำถามที่ผู้ตรวจถามแน่",
              en: "You must distinguish **DiamondTrap's own name** from `ClapTrap::_name`, which is set to `<name>_clap_name` — an evaluator will ask about exactly this." },
      data: "\"I am Zaz, and my ClapTrap name is Zaz_clap_name\"",
      vars: [ { n: "_name", d: { th: "ของ DiamondTrap เอง คนละตัวกับของแม่", en: "DiamondTrap's own, distinct from the base's" } } ] },
    { fn: "destructor ทำงานย้อนกลับ", file: "ทุกไฟล์", depth: 0,
      note: { th: "**สร้างจากล่างขึ้นบน ทำลายจากบนลงล่าง** — DiamondTrap ก่อน แล้ว FragTrap, ScavTrap และ ClapTrap ปิดท้าย ผู้ตรวจให้ดูลำดับข้อความที่พิมพ์ออกมา",
              en: "**Constructed bottom-up, destroyed top-down** — DiamondTrap first, then FragTrap, ScavTrap and finally ClapTrap; the evaluator reads the printed order." },
      data: "~DiamondTrap -> ~FragTrap -> ~ScavTrap -> ~ClapTrap",
      vars: [ { n: "order", d: { th: "ตรงข้ามกับตอนสร้างเสมอ", en: "always the exact reverse of construction" } } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_04 = {
  input: "const Animal *a = new Dog();  a->makeSound();  delete a;",
  steps: [
    { fn: "new Dog()", file: "Dog.cpp", depth: 0,
      note: { th: "สร้าง `Animal` ก่อนแล้วค่อย `Dog` — และ `Dog` จองสมอง (`Brain`) บน heap ในตัว constructor ของมันเอง",
              en: "`Animal` is constructed first, then `Dog` — which allocates its `Brain` on the heap inside its own constructor." },
      data: "Animal() -> Dog()  ->  _brain = new Brain();",
      vars: [ { n: "_brain", d: { th: "ทรัพยากรที่ต้องมีเจ้าของชัดเจน", en: "a resource that needs an explicit owner" }, w: true } ] },
    { fn: "a->makeSound()", file: "Animal.hpp", depth: 0,
      note: { th: "ตัวแปรมีชนิดเป็น `Animal *` แต่เรียกแล้วได้เสียงหมา เพราะ `makeSound` เป็น **virtual** — การเลือกฟังก์ชันเกิดตอน **runtime** จากชนิดจริงของอ็อบเจกต์",
              en: "The variable is an `Animal *` yet a dog barks, because `makeSound` is **virtual** — the choice happens at **runtime** from the object's real type." },
      data: "\"Woof!\"   (ไม่ใช่เสียงกลางของ Animal)",
      vars: [ { n: "vptr", d: { th: "ตัวชี้ตารางฟังก์ชันที่คอมไพเลอร์ฝังไว้ในอ็อบเจกต์", en: "the hidden pointer to the function table the compiler embeds" } } ] },
    { fn: "ถ้าไม่ใส่ virtual", file: "Animal.hpp", depth: 1,
      note: { th: "จะได้เสียงของ `Animal` แทน เพราะการเลือกเกิดตอน **compile time** จากชนิดของตัวแปร — นี่คือความต่างระหว่าง static กับ dynamic dispatch",
              en: "You would get `Animal`'s sound instead, because the choice is made at **compile time** from the variable's type — that is static versus dynamic dispatch." },
      data: "WrongAnimal / WrongCat สาธิตเคสนี้ตรง ๆ",
      vars: [ { n: "static vs dynamic", d: { th: "โจทย์ให้เขียนทั้งสองแบบเพื่อให้เห็นความต่าง", en: "the subject makes you write both so the difference is visible" } } ] },
    { fn: "deep copy: Dog b = *dog", file: "Dog.cpp", depth: 0,
      note: { th: "copy constructor เริ่มต้นจะคัดลอก **ตัวชี้** ทำให้สองอ็อบเจกต์ถือ `Brain` ก้อนเดียวกัน แล้ว `delete` สองครั้งตอนจบ — ต้องเขียนเองให้ `new Brain(*o._brain)`",
              en: "The default copy constructor copies the **pointer**, so two objects share one `Brain` and both delete it — write it yourself as `new Brain(*o._brain)`." },
      data: "_brain = new Brain(*other._brain);   // สมองคนละก้อน",
      vars: [ { n: "double free", d: { th: "อาการของ shallow copy ที่ valgrind จับได้ทันที", en: "the shallow-copy symptom valgrind catches immediately" }, w: true } ] },
    { fn: "delete a", file: "main.cpp", depth: 0,
      note: { th: "`a` มีชนิดเป็น `Animal *` ถ้า destructor ของ `Animal` **ไม่ virtual** จะเรียกแค่ `~Animal` แล้ว `Brain` รั่วทันที — นี่คือเหตุผลที่คลาสฐานที่มีลูกต้องมี virtual destructor เสมอ",
              en: "`a` is an `Animal *`; if `Animal`'s destructor is **not virtual**, only `~Animal` runs and the `Brain` leaks — which is why a base class with children always needs a virtual destructor." },
      data: "virtual ~Animal();   ->  ~Dog() -> ~Brain() -> ~Animal()",
      vars: [ { n: "leak", v: "0", d: { th: "virtual destructor คือสิ่งเดียวที่กันได้", en: "the virtual destructor is the only thing that prevents it" }, w: true } ] },
    { fn: "abstract class", file: "AAnimal.hpp", depth: 0,
      note: { th: "ใส่ `= 0` ให้ method ทำให้คลาสกลายเป็น **abstract** สร้างอินสแตนซ์ตรง ๆ ไม่ได้ — เหมาะกับกรณีที่ 'Animal ลอย ๆ' ไม่มีความหมาย",
              en: "Marking a method `= 0` makes the class **abstract**: it cannot be instantiated directly — right when a bare 'Animal' has no meaning." },
      data: "virtual void makeSound() const = 0;",
      vars: [ { n: "AAnimal a;", d: { th: "คอมไพล์ไม่ผ่าน และนั่นคือสิ่งที่ต้องการ", en: "fails to compile, which is the point" } } ] },
    { fn: "interface: ICharacter / IMateriaSource", file: "ex03", depth: 0,
      note: { th: "คลาสที่มีแต่ pure virtual = **สัญญา** ไม่มีข้อมูลและไม่มีการทำงาน ใครจะ implement ยังไงก็ได้ ตราบใดที่ทำครบตามสัญญา",
              en: "A class of nothing but pure virtuals is a **contract**: no data, no behaviour, and any implementation is free as long as it fulfils the contract." },
      data: "class ICharacter { public: virtual ~ICharacter() {} virtual void equip(AMateria *) = 0; ... };",
      vars: [ { n: "virtual ~", d: { th: "interface ก็ยังต้องมี virtual destructor", en: "an interface still needs a virtual destructor" } } ] },
    { fn: "unequip แล้วใครเป็นเจ้าของ", file: "Character.cpp", depth: 1,
      note: { th: "`unequip` **ห้าม delete** ตามโจทย์ — ต้องเก็บ pointer ไว้ไม่ให้หายเพื่อ delete ตอน destructor ไม่งั้นคือ leak ที่ตั้งใจวางไว้ให้พลาด",
              en: "`unequip` **must not delete** per the subject — keep the pointer somewhere so the destructor can free it, or you leak exactly where the trap was set." },
      data: "_floor[n] = _inventory[idx];   _inventory[idx] = NULL;",
      vars: [ { n: "ownership", d: { th: "ต้องตอบให้ได้ว่าใครเป็นคนลบและลบเมื่อไหร่", en: "you must be able to say who deletes it, and when" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_05 = {
  input: "Bureaucrat bob(\"Bob\", 3);  ShrubberyCreationForm f(\"home\");  bob.signForm(f);",
  steps: [
    { fn: "Bureaucrat(name, grade)", file: "Bureaucrat.cpp", depth: 0,
      note: { th: "เกรด 1 สูงสุด 150 ต่ำสุด — นอกช่วงต้อง **throw จาก constructor** ซึ่งแปลว่าอ็อบเจกต์นั้นไม่เคยเกิดขึ้นเลย และ destructor ของมันจะไม่ถูกเรียก",
              en: "Grade 1 is highest and 150 lowest; out of range must **throw from the constructor**, which means the object never existed and its destructor never runs." },
      data: "grade = 3   ok",
      vars: [ { n: "_grade", v: "3", d: { th: "เป็น const ตอนไหน เป็น `_name` ที่เปลี่ยนไม่ได้", en: "`_name` is const; the grade is not" }, w: true } ] },
    { fn: "throw จาก constructor", file: "Bureaucrat.cpp", depth: 1,
      note: { th: "สมาชิกที่สร้างเสร็จแล้วจะถูกทำลายให้ **แต่ตัวอ็อบเจกต์เองไม่ถูกนับว่าสร้างสำเร็จ** — ถ้าจองอะไรไว้เองก่อน throw ต้องคืนเอง ไม่มีใครมาคืนให้",
              en: "Already-constructed members are destroyed, but **the object itself never counts as constructed** — anything you allocated before the throw must be released by hand." },
      data: "throw Bureaucrat::GradeTooHighException();",
      vars: [ { n: "~Bureaucrat", v: "ไม่ถูกเรียก", d: { th: "เพราะไม่เคยสร้างสำเร็จ", en: "because construction never completed" } } ] },
    { fn: "const member ปะทะ OCF", file: "Bureaucrat.hpp", depth: 1,
      note: { th: "`const std::string _name` ทำให้ **copy assignment เขียนทับชื่อไม่ได้** — ต้องเลือกว่าจะคัดลอกเฉพาะเกรด หรือประกาศ operator= แล้วอธิบายข้อจำกัดนี้ให้ผู้ตรวจฟัง",
              en: "A `const std::string _name` means **copy assignment cannot overwrite the name** — either copy only the grade, or declare the operator and be ready to explain the limitation." },
      data: "Bureaucrat &operator=(const Bureaucrat &o) { _grade = o._grade; return *this; }",
      vars: [ { n: "_name", d: { th: "ตั้งได้ครั้งเดียวใน initializer list", en: "settable only once, in the initializer list" } } ] },
    { fn: "signForm(f)", file: "Bureaucrat.cpp", depth: 0,
      note: { th: "จับ exception ตรงนี้เองแล้วพิมพ์เหตุผล — **การโยนกับการจัดการเป็นคนละที่กัน** คือประโยชน์ทั้งหมดของ exception: ชั้นล่างไม่ต้องรู้ว่าจะรายงานยังไง",
              en: "The exception is caught here and the reason printed — **throwing and handling live in different places**, which is the entire benefit: the lower layer need not know how to report." },
      data: "try { f.beSigned(*this); } catch (std::exception &e) { ... }",
      vars: [ { n: "catch (std::exception &)", d: { th: "จับด้วย reference เสมอ กัน object slicing", en: "always catch by reference, to avoid slicing" } } ] },
    { fn: "AForm::beSigned(b)", file: "AForm.cpp", depth: 1,
      note: { th: "เทียบเกรดของ bureaucrat กับ `_gradeToSign` แล้ว **โยนถ้าต่ำไป** — ตัวฟอร์มไม่รู้จักการพิมพ์ข้อความ มันแค่บอกว่าทำไม่ได้",
              en: "Compare the bureaucrat's grade against `_gradeToSign` and **throw if it is too low** — the form knows nothing about printing; it only reports that it cannot be done." },
      data: "if (b.getGrade() > _gradeToSign) throw GradeTooLowException();",
      vars: [ { n: "_signed", v: "true", d: { th: "เปลี่ยนได้เพราะไม่ใช่ const ต่างจาก _gradeToSign", en: "mutable, unlike the const _gradeToSign" }, w: true } ] },
    { fn: "execute(executor)", file: "AForm.cpp", depth: 0,
      note: { th: "**template method**: คลาสฐานตรวจเงื่อนไข (เซ็นแล้วหรือยัง เกรดพอไหม) แล้วค่อยเรียก `_execute()` ที่ลูกเขียนเอง — กติกาอยู่ที่เดียว ลูกเขียนแต่เนื้องาน",
              en: "A **template method**: the base checks the conditions (signed? grade high enough?) and only then calls the child's `_execute()` — the rules live in one place and children write only the work." },
      data: "if (!_signed) throw NotSignedException();",
      vars: [ { n: "_execute", d: { th: "pure virtual ที่ลูกต้อง implement", en: "the pure virtual each child implements" } } ] },
    { fn: "ShrubberyCreationForm::_execute", file: "Shrubbery.cpp", depth: 1,
      note: { th: "สร้างไฟล์ `<target>_shrubbery` แล้ววาดต้นไม้ ASCII — ตรงนี้คือเหตุผลที่ต้องแยก `execute` ออกจาก `_execute`: การตรวจสิทธิ์ไม่ควรปนกับงานจริง",
              en: "Writes `<target>_shrubbery` with an ASCII tree — precisely why `execute` and `_execute` are separate: permission checks should not mix with the work itself." },
      data: "std::ofstream out((_target + \"_shrubbery\").c_str());",
      vars: [ { n: "out", d: { th: "RAII ปิดไฟล์เองตอนจบ scope", en: "RAII closes the file at end of scope" }, w: true } ] },
    { fn: "Intern::makeForm(name, target)", file: "Intern.cpp", depth: 0,
      note: { th: "ห้ามใช้ if-else ซ้อนยาว — ใช้ **array ของชื่อคู่กับ array ของฟังก์ชันสร้าง** แล้ววนหาดัชนี เพิ่มฟอร์มใหม่ก็แค่เพิ่มแถว ไม่ต้องแก้ตรรกะ",
              en: "Avoid a long if-else chain: use **an array of names beside an array of factory functions** and look up the index — a new form is one more row, not a logic change." },
      data: "AForm *(*maker[3])(std::string) = { &makeShrub, &makeRobot, &makePardon };",
      vars: [ { n: "return", d: { th: "ผู้เรียกเป็นเจ้าของ ต้อง delete เอง", en: "the caller owns it and must delete it" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_06 = {
  input: "ScalarConverter::convert(\"42.0f\");  Base *p = generate();  identify(p);",
  steps: [
    { fn: "ScalarConverter::convert(str)", file: "ScalarConverter.cpp", depth: 0,
      note: { th: "ตรวจก่อนว่าอินพุตเป็นชนิดไหนใน 4 ชนิด (char, int, float, double) แล้วค่อยแปลงต่อ — คลาสนี้ **ห้ามสร้างอินสแตนซ์** จึงทำ constructor เป็น private",
              en: "First decide which of the four literal types the input is (char, int, float, double), then convert — and the class **must not be instantiable**, so its constructor is private." },
      data: "\"42.0f\"  ->  ลงท้ายด้วย f และมีจุด  ->  float",
      vars: [ { n: "type", v: "FLOAT", d: { th: "ตัดสินจากรูปแบบของสตริงล้วน ๆ", en: "decided purely from the string's shape" }, w: true } ] },
    { fn: "pseudo literal", file: "ScalarConverter.cpp", depth: 1,
      note: { th: "`nan`, `+inf`, `-inf`, `nanf`, `+inff`, `-inff` ต้องรับได้และแปลงเป็น char/int **ไม่ได้** ต้องรายงานว่า impossible — เป็นเคสที่คนลืมบ่อยที่สุด",
              en: "`nan`, `+inf`, `-inf` and their `f` variants must be accepted, and converting them to char or int is **impossible** and must be reported as such — the most commonly forgotten case." },
      data: "\"nan\" -> char: impossible  int: impossible  float: nanf  double: nan",
      vars: [ { n: "impossible", d: { th: "ต่างจาก 'Non displayable' ซึ่งใช้กับ char ที่พิมพ์ไม่ได้", en: "different from 'Non displayable', which is for unprintable chars" } } ] },
    { fn: "static_cast", file: "ScalarConverter.cpp", depth: 1,
      note: { th: "แปลงระหว่างชนิดที่ **เกี่ยวข้องกัน** และตรวจได้ตอนคอมไพล์ — เป็นตัวที่ควรใช้เป็นค่าเริ่มต้น เพราะปลอดภัยที่สุดในบรรดา cast ทั้งสี่",
              en: "Converts between **related** types with compile-time checking — the default choice, because it is the safest of the four casts." },
      data: "static_cast<int>(42.0f) = 42",
      vars: [ { n: "range check", d: { th: "ต้องเช็คก่อนว่าค่ายังอยู่ในช่วงของชนิดปลายทาง", en: "check the value still fits the destination type first" } } ] },
    { fn: "reinterpret_cast", file: "Serializer.cpp", depth: 0,
      note: { th: "**ตีความบิตชุดเดิมเป็นชนิดใหม่** โดยไม่แปลงค่าอะไรเลย — ใช้กับ pointer ↔ integer อย่างที่ `serialize`/`deserialize` ทำ และเป็น cast ที่อันตรายที่สุด",
              en: "**Reinterprets the same bits as another type** without converting anything — used for pointer ↔ integer as `serialize`/`deserialize` do, and the most dangerous of the casts." },
      data: "uintptr_t raw = reinterpret_cast<uintptr_t>(ptr);",
      vars: [ { n: "uintptr_t", d: { th: "ชนิดเดียวที่รับประกันว่าเก็บ pointer ได้ครบ", en: "the only type guaranteed to hold a pointer" } } ] },
    { fn: "deserialize(raw)", file: "Serializer.cpp", depth: 1,
      note: { th: "แปลงกลับได้ค่าเดิมเป๊ะเพราะ **ไม่มีการแปลงค่า มีแต่การตีความ** — เทียบ pointer ก่อนกับหลังต้องได้ตัวเดียวกัน นั่นคือสิ่งที่ main ต้องพิสูจน์",
              en: "The round trip is exact because **nothing is converted, only reinterpreted** — the pointer before and after must compare equal, and main must demonstrate it." },
      data: "reinterpret_cast<Data *>(raw) == ptr   ->  true",
      vars: [ { n: "round trip", v: "exact", d: { th: "ไม่ใช่การคัดลอกอ็อบเจกต์ แค่ตัวเลขเดิม", en: "not an object copy, just the same number" } } ] },
    { fn: "dynamic_cast<Base *>", file: "identify.cpp", depth: 0,
      note: { th: "ถามตอน **runtime** ว่าอ็อบเจกต์นี้เป็นชนิดลูกตัวไหน ทำได้เพราะคลาสมี virtual function จึงมี **RTTI** ติดมาด้วย — ถ้าไม่มี virtual เลยจะ cast ไม่ได้",
              en: "Asks at **runtime** which derived type an object really is, which works because the class has virtual functions and therefore **RTTI** — with no virtual member at all, the cast is not possible." },
      data: "if (dynamic_cast<A *>(p)) std::cout << \"A\";",
      vars: [ { n: "p", d: { th: "ชนิดตอนคอมไพล์คือ Base * แต่ชนิดจริงคือ A", en: "its compile-time type is Base *, its real type is A" } } ] },
    { fn: "รุ่น pointer เทียบรุ่น reference", file: "identify.cpp", depth: 1,
      note: { th: "รุ่น pointer **คืน NULL** เมื่อไม่ใช่ชนิดนั้น จึงเช็คด้วย if ได้ ส่วนรุ่น reference **โยน `std::bad_cast`** เพราะ reference เป็น NULL ไม่ได้ — ต้องใช้ try/catch",
              en: "The pointer form **returns NULL** when the type does not match, so an if suffices; the reference form **throws `std::bad_cast`**, because a reference cannot be null — so it needs try/catch." },
      data: "try { A &a = dynamic_cast<A &>(r); } catch (std::bad_cast &) { }",
      vars: [ { n: "bad_cast", d: { th: "เหตุผลที่ต้องเขียนสองเวอร์ชันในโจทย์", en: "why the subject asks for both versions" } } ] },
    { fn: "const_cast — ตัวที่สี่", file: "หมายเหตุ", depth: 1,
      note: { th: "ถอด `const` ออกจาก pointer หรือ reference — โจทย์ไม่ได้บังคับใช้ แต่ผู้ตรวจมักถามให้ครบสี่ตัว และการเขียนทับค่าที่ **เป็น const จริง ๆ** คือ undefined behaviour",
              en: "Strips `const` from a pointer or reference — not required by the subject, but evaluators ask for all four, and writing through it to a genuinely const object is undefined behaviour." },
      data: "char *w = const_cast<char *>(readOnly);   // เขียนลงไป = UB",
      vars: [ { n: "4 casts", d: { th: "static, reinterpret, dynamic, const", en: "static, reinterpret, dynamic, const" } } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_07 = {
  input: "Array<int> a(5);  a[2] = 42;  Array<int> b = a;  b[2] = 7;",
  steps: [
    { fn: "template <typename T>", file: "Array.hpp", depth: 0,
      note: { th: "template คือ **แม่พิมพ์** ไม่ใช่โค้ดจริง — คอมไพเลอร์จะสร้างโค้ดขึ้นมาต่อชนิดที่ถูกใช้จริงเท่านั้น เรียกว่า instantiation",
              en: "A template is a **mould, not code** — the compiler generates a version only for the types actually used, which is called instantiation." },
      data: "Array<int> -> คอมไพเลอร์สร้างคลาสสำหรับ int ขึ้นมา",
      vars: [ { n: "T", v: "int", d: { th: "ถูกแทนที่ตอนคอมไพล์ ไม่มีต้นทุนตอนรัน", en: "substituted at compile time, with no runtime cost" } } ] },
    { fn: "ทำไมต้องอยู่ใน header", file: "Array.hpp", depth: 1,
      note: { th: "คอมไพเลอร์ต้องเห็น **โค้ดเต็ม** ตอนที่พบการใช้งาน จึงจะสร้างเวอร์ชันของชนิดนั้นได้ — แยกไป `.cpp` แล้วจะได้ undefined reference ตอน link",
              en: "The compiler must see the **full body** where the template is used in order to generate that version — split it into a `.cpp` and you get an undefined reference at link time." },
      data: "template ทั้งหมดอยู่ใน .hpp (หรือ .tpp ที่ถูก include ท้ายไฟล์)",
      vars: [ { n: "link error", d: { th: "อาการคลาสสิกของการแยก template ไป .cpp", en: "the classic symptom of splitting a template into a .cpp" } } ] },
    { fn: "Array(unsigned int n)", file: "Array.hpp", depth: 0,
      note: { th: "`new T[n]()` — วงเล็บท้ายทำให้สมาชิกถูก **value-initialize** เป็นค่าเริ่มต้นของชนิดนั้น (0 สำหรับ int) ตามที่โจทย์บังคับ",
              en: "`new T[n]()` — the trailing parentheses **value-initialize** every element to that type's default (0 for int), exactly as the subject requires." },
      data: "_data = new int[5]();   _size = 5;",
      vars: [ { n: "_data", d: { th: "ต้องคู่กับ delete[] เท่านั้น", en: "must be paired with delete[], never delete" }, w: true } ] },
    { fn: "operator[](i)", file: "Array.hpp", depth: 0,
      note: { th: "ต้อง **โยน exception เมื่อ index เกินขอบเขต** ต่างจาก array ธรรมดาที่เงียบแล้วพังทีหลัง และต้องมีสองเวอร์ชัน: const กับไม่ const",
              en: "It must **throw when the index is out of range**, unlike a raw array that stays silent and breaks later — and it needs two versions, const and non-const." },
      data: "if (i >= _size) throw std::exception();",
      vars: [ { n: "const version", d: { th: "อ่านอย่างเดียวจากอ็อบเจกต์ที่เป็น const", en: "read-only access on a const object" } } ] },
    { fn: "Array<int> b = a", file: "Array.hpp", depth: 0,
      note: { th: "**deep copy บังคับ**: จองบล็อกใหม่แล้วคัดลอกทีละตัว ถ้าปล่อยให้คัดลอกตัวชี้ สองอ็อบเจกต์จะใช้บล็อกเดียวกันแล้ว `delete[]` สองครั้ง",
              en: "**A deep copy is mandatory**: allocate a new block and copy element by element, or both objects share one block and both delete it." },
      data: "_data = new T[o._size];  for (i) _data[i] = o._data[i];",
      vars: [ { n: "b._data", d: { th: "คนละที่อยู่กับ a._data", en: "a different address from a._data" }, w: true } ] },
    { fn: "b[2] = 7  แล้ว a[2] ล่ะ", file: "main.cpp", depth: 1,
      note: { th: "ยังเป็น 42 อยู่ — **นี่คือการพิสูจน์ว่า deep copy ทำงานจริง** และเป็นเทสต์ที่ผู้ตรวจสั่งให้เขียนสด ๆ ได้",
              en: "It is still 42 — **this is the proof the deep copy works**, and the test an evaluator may ask you to write on the spot." },
      data: "a[2] == 42   b[2] == 7",
      vars: [ { n: "independence", d: { th: "ถ้าเปลี่ยนตามกันคือ shallow copy", en: "if they change together, the copy was shallow" }, w: true } ] },
    { fn: "iter(array, len, f)", file: "iter.hpp", depth: 0,
      note: { th: "template ของ **ฟังก์ชัน** ที่รับฟังก์ชันอีกทีเป็นพารามิเตอร์ — ต้องรองรับทั้งเวอร์ชัน const และไม่ const ของตัว callback",
              en: "A **function** template that takes another function as a parameter — and it must work with both const and non-const callbacks." },
      data: "template <typename T> void iter(T *a, size_t n, void (*f)(T &));",
      vars: [ { n: "f", d: { th: "คอมไพเลอร์อนุมานชนิด T ให้เองจาก argument", en: "the compiler deduces T from the argument" } } ] },
    { fn: "swap / min / max", file: "whatever.hpp", depth: 0,
      note: { th: "ทั้งสามตัวรับ **reference ไม่ใช่สำเนา** เพราะ `swap` ต้องแก้ของจริง และ `min`/`max` ต้องคืน reference เพื่อให้นำไปเขียนต่อได้ — เมื่อเท่ากันโจทย์ให้คืนตัวที่สอง",
              en: "All three take **references, not copies**: `swap` must modify the originals, and `min`/`max` return references so the result can be assigned to — and on a tie the subject wants the second." },
      data: "template <typename T> T &max(T &a, T &b) { return (a > b ? b : a); }",
      vars: [ { n: "operator>", d: { th: "ชนิด T ต้องเปรียบเทียบได้ ไม่งั้นคอมไพล์ไม่ผ่าน", en: "T must be comparable, or it will not compile" } } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_08 = {
  input: "easyfind(std::vector<int>(...), 42);  Span sp(10000);  sp.shortestSpan();",
  steps: [
    { fn: "easyfind(T &container, int v)", file: "easyfind.hpp", depth: 0,
      note: { th: "รับ container **ชนิดใดก็ได้** ที่มี iterator — นี่คือหัวใจของ STL: algorithm ไม่รู้จักโครงสร้างข้อมูล มันรู้จักแค่ iterator",
              en: "Takes **any** container that provides iterators — the core idea of the STL: an algorithm knows nothing about the data structure, only about iterators." },
      data: "std::find(c.begin(), c.end(), 42)",
      vars: [ { n: "T", d: { th: "vector, list, deque ใช้โค้ดเดียวกันได้หมด", en: "vector, list and deque all reuse the same code" } } ] },
    { fn: "typename T::iterator", file: "easyfind.hpp", depth: 1,
      note: { th: "ต้องใส่ `typename` เพราะ `T::iterator` เป็น **dependent name** — คอมไพเลอร์ยังไม่รู้ว่าเป็นชนิดหรือเป็นค่า จึงต้องบอกให้ชัดว่านี่คือชนิด",
              en: "`typename` is required because `T::iterator` is a **dependent name** — the compiler cannot yet tell a type from a value, so you must say which." },
      data: "typename T::iterator it = std::find(...);",
      vars: [ { n: "typename", d: { th: "ลืมแล้วได้ error ที่อ่านไม่รู้เรื่องเลย", en: "forget it and the error message is unreadable" } } ] },
    { fn: "ไม่เจอ -> คืน end()", file: "easyfind.hpp", depth: 1,
      note: { th: "`end()` คือ **ตำแหน่งถัดจากตัวสุดท้าย** ไม่ใช่ตัวสุดท้าย — ห้าม dereference และการเทียบกับมันคือวิธีมาตรฐานในการบอกว่า 'ไม่เจอ'",
              en: "`end()` is **one past the last element**, not the last one — never dereference it; comparing against it is the standard way to say 'not found'." },
      data: "if (it == c.end()) throw std::exception();",
      vars: [ { n: "end()", d: { th: "half-open range [begin, end) เป็นแบบแผนของ STL ทั้งหมด", en: "the half-open range [begin, end) is the STL's universal convention" } } ] },
    { fn: "Span::addNumber(n)", file: "Span.cpp", depth: 0,
      note: { th: "เก็บใน `std::vector` แล้วโยน exception เมื่อเต็ม — ความจุถูกกำหนดตอนสร้างและเปลี่ยนไม่ได้ ซึ่งเป็นสัญญาที่คลาสนี้รับปาก",
              en: "Stored in a `std::vector`, throwing when full — the capacity is fixed at construction, which is the promise this class makes." },
      data: "if (_v.size() >= _n) throw std::exception();",
      vars: [ { n: "_v", d: { th: "vector โตเองได้ แต่เราจำกัดด้วยกติกาของคลาส", en: "the vector could grow, but the class's rule caps it" }, w: true } ] },
    { fn: "addNumber(begin, end) — ทีละช่วง", file: "Span.cpp", depth: 1,
      note: { th: "ใส่ทีละตัวสำหรับหนึ่งหมื่นตัวคือช้าและน่าเกลียด — รับ iterator สองตัวแล้ว `insert` ทีเดียว เร็วกว่าและเป็นสำนวน STL",
              en: "Adding ten thousand numbers one at a time is slow and ugly — take a pair of iterators and `insert` once, which is both faster and idiomatic." },
      data: "_v.insert(_v.end(), first, last);",
      vars: [ { n: "capacity", d: { th: "ยังต้องเช็คว่าใส่แล้วไม่เกินความจุ", en: "still check the total stays within capacity" }, w: true } ] },
    { fn: "longestSpan()", file: "Span.cpp", depth: 0,
      note: { th: "คือ **มากสุดลบน้อยสุด** ใช้ `std::max_element` กับ `std::min_element` เดินครบทั้งชุดสองรอบ = O(n) ไม่ต้องเรียงเลย",
              en: "It is simply **max minus min**: `std::max_element` and `std::min_element`, two linear passes, O(n), with no sorting at all." },
      data: "*max_element(v.begin(), v.end()) - *min_element(...)",
      vars: [ { n: "O(n)", d: { th: "อย่าเรียงถ้าไม่จำเป็น", en: "do not sort when you do not have to" } } ] },
    { fn: "shortestSpan()", file: "Span.cpp", depth: 0,
      note: { th: "**คู่ที่ห่างกันน้อยที่สุดต้องอยู่ติดกันหลังเรียง** จึงเรียงสำเนาแล้วไล่ดูผลต่างของเพื่อนบ้าน — O(n log n) แทนที่จะเทียบทุกคู่แบบ O(n²)",
              en: "**The closest pair must be adjacent once sorted**, so sort a copy and scan neighbouring differences — O(n log n) instead of comparing every pair at O(n²)." },
      data: "std::sort(copy.begin(), copy.end());  min(copy[i+1] - copy[i])",
      vars: [ { n: "copy", d: { th: "เรียงสำเนา ไม่แตะลำดับเดิมของผู้ใช้", en: "sort a copy; do not disturb the user's order" }, w: true } ] },
    { fn: "MutantStack: iterator จาก stack", file: "MutantStack.hpp", depth: 0,
      note: { th: "`std::stack` เป็น **container adaptor** ที่ซ่อน container จริงไว้ใน member ชื่อ `c` ซึ่งเป็น `protected` — สืบทอดแล้วจึงเข้าถึงได้ และยืม iterator ของมันมาใช้เลย",
              en: "`std::stack` is a **container adaptor** hiding the real container in a `protected` member named `c` — inherit from it and you can reach `c` and simply borrow its iterators." },
      data: "typedef typename std::stack<T>::container_type::iterator iterator;\niterator begin() { return this->c.begin(); }",
      vars: [ { n: "c", d: { th: "protected จึงเข้าถึงได้เฉพาะจากคลาสลูก", en: "protected, so only a derived class can reach it" }, w: true } ] }
  ]
};

window.EXTRA_FLOWS.cpp_module_09 = {
  input: "./RPN \"8 9 * 9 - 9 - 9 - 4 - 1 +\"   และ  ./PmergeMe 3 5 9 7 4",
  steps: [
    { fn: "BitcoinExchange: โหลด data.csv", file: "BitcoinExchange.cpp", depth: 0,
      note: { th: "เก็บใน `std::map<std::string, float>` ซึ่ง **เรียงตาม key อัตโนมัติ** — วันที่ในรูป `YYYY-MM-DD` เรียงตามตัวอักษรแล้วได้ลำดับเวลาพอดี ซึ่งเป็นเหตุผลที่ใช้รูปแบบนี้",
              en: "Kept in a `std::map<std::string, float>`, which is **sorted by key automatically** — and `YYYY-MM-DD` sorts lexicographically into chronological order, which is exactly why that format is used." },
      data: "map[\"2011-01-03\"] = 0.3",
      vars: [ { n: "std::map", d: { th: "red-black tree ค้นหา O(log n)", en: "a red-black tree, O(log n) lookup" }, w: true } ] },
    { fn: "หาวันที่ที่ใกล้ที่สุดก่อนหน้า", file: "BitcoinExchange.cpp", depth: 1,
      note: { th: "`lower_bound` คืนตัวแรกที่ **ไม่น้อยกว่า** ที่ขอ ถ้าไม่ตรงเป๊ะต้องถอยหนึ่งช่องเพื่อได้วันก่อนหน้า — และถ้าถอยแล้วชน `begin()` แปลว่าไม่มีข้อมูลเก่ากว่านั้น",
              en: "`lower_bound` returns the first key **not less than** the one asked for; if it is not an exact match, step back one for the earlier date — and hitting `begin()` means no earlier data exists." },
      data: "it = db.lower_bound(date);  if (it->first != date) --it;",
      vars: [ { n: "--it", d: { th: "ต้องเช็ค `it != db.begin()` ก่อนเสมอ", en: "always check `it != db.begin()` first" } } ] },
    { fn: "ตรวจอินพุตให้ครบ", file: "BitcoinExchange.cpp", depth: 1,
      note: { th: "รูปแบบบรรทัดผิด, วันที่ไม่มีจริง (2012-02-31), ค่าติดลบ, ค่ามากกว่า 1000 — แต่ละกรณีมีข้อความของตัวเองและ **ต้องไม่หยุดโปรแกรม** ทำต่อบรรทัดถัดไป",
              en: "Bad line shape, an impossible date (2012-02-31), a negative value, a value above 1000 — each has its own message, and none may **stop the program**; carry on to the next line." },
      data: "\"Error: bad input => 2001-42-42\"",
      vars: [ { n: "continue", d: { th: "รายงานแล้วไปต่อ ไม่ใช่ throw ออกทั้งโปรแกรม", en: "report and continue, rather than throwing out of the program" } } ] },
    { fn: "RPN: อ่านโทเค็นทีละตัว", file: "RPN.cpp", depth: 0,
      note: { th: "`std::stack` เหมาะพอดีเพราะ RPN ทำงานแบบ **เข้าหลังออกก่อน** — เจอตัวเลข push, เจอเครื่องหมาย pop สองตัวมาคำนวณแล้ว push ผลกลับ",
              en: "`std::stack` fits exactly, because RPN is **last in, first out** — push a number, and on an operator pop two, compute, and push the result back." },
      data: "8 9 *  ->  push 8, push 9, pop 9 & 8 -> 72",
      vars: [ { n: "stack", v: "[72]", d: { th: "ผลลัพธ์ระหว่างทางกลับเข้า stack เสมอ", en: "each intermediate result goes straight back on the stack" }, w: true } ] },
    { fn: "ลำดับของตัวถูกดำเนินการ", file: "RPN.cpp", depth: 1,
      note: { th: "ตัวที่ pop ออก **ก่อน** คือตัวขวาของนิพจน์ — สลับลำดับแล้วบวกกับคูณยังถูก แต่ลบกับหารจะผิดทันที เป็นบั๊กที่หายากเพราะเทสต์ครึ่งหนึ่งยังผ่าน",
              en: "The value popped **first** is the right-hand operand — swap them and addition and multiplication still look fine while subtraction and division break, a bug that hides because half the tests still pass." },
      data: "b = pop(); a = pop();  ->  a - b",
      vars: [ { n: "หารด้วยศูนย์", d: { th: "ต้องตรวจก่อนหาร", en: "must be checked before dividing" } } ] },
    { fn: "PmergeMe: จับคู่", file: "PmergeMe.cpp", depth: 0,
      note: { th: "Ford-Johnson เริ่มด้วยการ **จับคู่แล้วเรียงในคู่** ได้ลำดับของตัวใหญ่มาชุดหนึ่ง ตัวเล็กอีกชุดรอถูกแทรกทีหลัง — จำนวนการเปรียบเทียบจึงต่ำกว่า merge sort ธรรมดา",
              en: "Ford-Johnson starts by **pairing and ordering within each pair**, giving a chain of larger elements and a set of smaller ones to insert later — which needs fewer comparisons than a plain merge sort." },
      data: "(3,5) (9,7) 4  ->  larger: 5, 9   smaller: 3, 7   ตกค้าง: 4",
      vars: [ { n: "odd one out", v: "4", d: { th: "จำนวนคี่จะเหลือตัวหนึ่งเสมอ ต้องจัดการแยก", en: "an odd count always leaves one over, handled separately" } } ] },
    { fn: "แทรกด้วยลำดับ Jacobsthal", file: "PmergeMe.cpp", depth: 1,
      note: { th: "ลำดับ 1, 3, 5, 11, 21 กำหนด **ลำดับการแทรก** ที่ทำให้ binary search แต่ละครั้งได้ข้อมูลมากที่สุด — นี่คือจุดที่อัลกอริทึมนี้ชนะ และเป็นจุดที่ต้องอธิบายได้",
              en: "The sequence 1, 3, 5, 11, 21 fixes the **insertion order** so each binary search extracts the most information — this is where the algorithm wins, and what you must be able to explain." },
      data: "แทรกตามลำดับ index: 1, 3, 2, 5, 4 ...",
      vars: [ { n: "binary insert", d: { th: "หาตำแหน่งด้วย O(log n) ไม่ใช่ไล่ทีละตัว", en: "locate the slot in O(log n), not by scanning" } } ] },
    { fn: "ทำสอง container แล้วจับเวลา", file: "PmergeMe.cpp", depth: 0,
      note: { th: "โจทย์บังคับให้ทำอัลกอริทึมเดียวกันบน **container สองชนิด** แล้วเทียบเวลา — `vector` ชนะเพราะข้อมูลอยู่ติดกันจึงเป็นมิตรกับ cache แม้ `deque` จะแทรกหัวถูกกว่าในทางทฤษฎี",
              en: "The subject demands the same algorithm on **two containers** with timings — `vector` usually wins because contiguous memory is cache friendly, even though `deque` is theoretically cheaper at the front." },
      data: "Time to process a range of 5 elements with std::vector : 0.00031 us",
      vars: [ { n: "clock()", d: { th: "จับเวลาเฉพาะส่วนเรียง ไม่รวมการอ่านอินพุต", en: "time the sort only, not the input parsing" }, w: true } ] }
  ]
};
